[package]
name = "radroots_nostr_runtime"
publish = false
version = "0.1.0-alpha"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Nostr runtime layer for Radroots"
repository.workspace = true
homepage.workspace = true
readme = "README"

[features]
default = ["std"]
std = []
rt = ["std", "dep:futures", "dep:tokio"]
nostr-client = ["std", "dep:nostr", "dep:radroots_nostr", "dep:radroots_transport_nostr"]
nostrdb = ["nostr-client"]

[dependencies]
radroots_nostr = { workspace = true, optional = true, default-features = true }
radroots_transport_nostr = { workspace = true, optional = true, default-features = false }
nostr = { workspace = true, optional = true, features = ["std"] }
futures = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true, features = ["rt", "sync", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
