[package]
name = "radroots_event"
publish = ["crates-io"]
version = "0.1.0-alpha"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Domain event model for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_event"
readme = "README"

[features]
default = ["std", "serde"]
dto-bindgen = [
  "std",
  "serde",
  "knowledge-nip54",
  "dep:dto_bindgen",
  "radroots_core/dto-bindgen",
]
knowledge = []
knowledge-nip54 = ["knowledge"]
signature = ["dep:secp256k1"]
std = ["radroots_blossom/std", "radroots_core/std", "url_nostd/std"]
serde = ["dep:serde", "radroots_core/serde"]

[dependencies]
dto_bindgen = { workspace = true, optional = true }
radroots_blossom = { workspace = true, default-features = false }
radroots_core = { workspace = true, default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
jiff-tzdb = { workspace = true }
serde = { workspace = true, default-features = false, features = [
  "alloc",
  "derive",
], optional = true }
serde_json = { workspace = true, default-features = false, features = [
  "alloc",
] }
secp256k1 = { workspace = true, optional = true }
sha2 = { workspace = true, default-features = false }
unicode-general-category = { workspace = true }
url_nostd = { workspace = true }

[dev-dependencies]
radroots_core = { workspace = true, default-features = false, features = [
  "serde",
  "std",
] }
serde = { workspace = true, default-features = false, features = [
  "alloc",
  "derive",
] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
