import { RadrootsComment, RadrootsFollow, RadrootsListing, RadrootsProfile, RadrootsReaction } from "./events/types.js";

/*
 Generated by typeshare 1.13.2
*/

export interface RadrootsNostrEvent {
	id: string;
	author: string;
	created_at: number;
	kind: number;
	tags: string[][];
	content: string;
	sig: string;
}

export interface RadrootsCommentEventMetadata {
	id: string;
	author: string;
	published_at: number;
	comment: RadrootsComment;
}

export interface RadrootsCommentEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsCommentEventMetadata;
}

export interface RadrootsFollowEventMetadata {
	id: string;
	author: string;
	published_at: number;
	follow: RadrootsFollow;
}

export interface RadrootsFollowEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsFollowEventMetadata;
}

export interface RadrootsIndexShardMetadata {
	file: string;
	count: number;
	first_id: string;
	last_id: string;
	first_published_at: number;
	last_published_at: number;
	sha256: string;
}

export interface RadrootsIndexManifest {
	country: string;
	total: number;
	shard_size: number;
	first_published_at: number;
	last_published_at: number;
	shards: RadrootsIndexShardMetadata[];
}

export interface RadrootsListingEventMetadata {
	id: string;
	author: string;
	published_at: number;
	listing: RadrootsListing;
}

export interface RadrootsListingEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsListingEventMetadata;
}

export interface RadrootsProfileEventMetadata {
	id: string;
	author: string;
	published_at: number;
	profile: RadrootsProfile;
}

export interface RadrootsProfileEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsProfileEventMetadata;
}

export interface RadrootsReactionEventMetadata {
	id: string;
	author: string;
	published_at: number;
	reaction: RadrootsReaction;
}

export interface RadrootsReactionEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsReactionEventMetadata;
}

