/*
 Generated by typeshare 1.13.2
*/

export interface ListingOrderQuantity {
	amount: number;
	unit: string;
	label: string;
	count: number;
}

export interface ListingOrderPrice {
	amount: number;
	currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrderDiscount {
	discount_type: string;
	threshold?: number;
	threshold_unit?: string;
	discount_per_unit?: number;
	discount_unit?: string;
	discount_percent?: number;
	discount_amount: number;
	currency: string;
}

export interface ListingOrderSubtotal {
	price_amount: number;
	price_currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrderTotal {
	price_amount: number;
	price_currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrder {
	quantity: ListingOrderQuantity;
	price: ListingOrderPrice;
	discounts: ListingOrderDiscount[];
	subtotal: ListingOrderSubtotal;
	total: ListingOrderTotal;
}

export interface ListingOrderRequestEvent {
	id: string;
}

export interface ListingOrderRequestPrice {
	amount: number;
	currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrderRequestQuantity {
	amount: number;
	unit: string;
	label: string;
	count: number;
}

export interface ListingOrderRequestPayload {
	price: ListingOrderRequestPrice;
	quantity: ListingOrderRequestQuantity;
}

export interface ListingOrderRequest {
	event: ListingOrderRequestEvent;
	payload: ListingOrderRequestPayload;
}

export interface RadrootsIndexShardMetadata {
	file: string;
	count: number;
	first_id: string;
	last_id: string;
	first_published_at: number;
	last_published_at: number;
	sha256: string;
}

export interface RadrootsIndexManifest {
	country: string;
	total: number;
	shard_size: number;
	first_published_at: number;
	last_published_at: number;
	shards: RadrootsIndexShardMetadata[];
}

export interface RadrootsNostrEvent {
	id: string;
	author: string;
	created_at: number;
	kind: number;
	tags: string[][];
	content: string;
	sig: string;
}

export interface RadrootsListingEventData {
	id: string;
	author: string;
	published_at: number;
	d_tag: string;
	title: string;
	summary: string;
	images: string[];
	location_address: string;
	location_city: string;
	location_region: string;
	location_country: string;
	location_lat: string;
	location_lng: string;
	location_geohash: string;
	product_kind: string;
	product_category: string;
	product_process: string;
	product_lot: string;
	product_profile: string;
	product_year: string;
	product_quantity_amt: string;
	product_quantity_unit: string;
	product_price_amt: string;
	product_price_cur: string;
	product_price_qty_amt: string;
	product_price_qty_unit: string;
}

export interface RadrootsListingEvent {
	event: RadrootsNostrEvent;
	data: RadrootsListingEventData;
}

export interface RadrootsMetadataEventDataMetadata {
	name: string;
	display_name?: string;
	nip05?: string;
	about?: string;
}

export interface RadrootsMetadataEventData {
	id: string;
	public_key: string;
	published_at: number;
	metadata: RadrootsMetadataEventDataMetadata;
}

export interface RadrootsMetadataEvent {
	event: RadrootsNostrEvent;
	data: RadrootsMetadataEventData;
}

export interface RadrootsNostrEventRef {
	ref_id: string;
	ref_author: string;
	ref_kind: number;
	ref_d_tag?: string;
}

export interface RadrootsNostrEvent1111Data {
	published_at: number;
	root: RadrootsNostrEventRef;
	parent: RadrootsNostrEventRef;
	content: string;
}

export interface RadrootsNostrEvent1111 {
	event: RadrootsNostrEvent;
	data: RadrootsNostrEvent1111Data;
}

export interface RadrootsNostrEvent3DataFollow {
	published_at: number;
	pubkey: string;
	relay_url?: string;
	petname?: string;
}

export interface RadrootsNostrEvent3Data {
	following: RadrootsNostrEvent3DataFollow[];
}

export interface RadrootsNostrEvent3 {
	event: RadrootsNostrEvent;
	data: RadrootsNostrEvent3Data;
}

export interface RadrootsNostrEvent7Data {
	published_at: number;
	root: RadrootsNostrEventRef;
	content: string;
}

export interface RadrootsNostrEvent7 {
	event: RadrootsNostrEvent;
	data: RadrootsNostrEvent7Data;
}

