[package]
name = "radroots_runtime"
publish = ["crates-io"]
version = "0.1.0-alpha.2"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Runtime configuration model for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_runtime"
readme = "README"

[features]
default = []
cli = ["dep:clap"]
transport = ["dep:radroots_event", "dep:radroots_transport"]
transport-nostr = ["transport"]
transport-reticulum = ["transport", "dep:radroots_transport_reticulum"]
transport-workers = ["transport"]

[dependencies]
anyhow = { workspace = true }
chacha20poly1305 = { workspace = true }
clap = { workspace = true, features = ["derive", "env"], optional = true }
config = { workspace = true }
getrandom = { workspace = true }
radroots_log = { workspace = true, features = ["std"] }
radroots_event = { workspace = true, optional = true, default-features = false, features = [
  "std",
  "serde",
] }
radroots_protected_store = { workspace = true, features = ["std"] }
radroots_runtime_paths = { workspace = true }
radroots_secret_vault = { workspace = true, features = ["std"] }
radroots_transport = { workspace = true, optional = true, default-features = false, features = [
  "serde",
] }
radroots_transport_reticulum = { workspace = true, optional = true, default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
toml = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }
