[package]
name = "radroots_log"
publish = false
version = "1.0.0-alpha.1"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Logging layer for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_log"
readme = "README"

[features]
default = ["std"]
std = [
  "tracing/std",
  "dep:chrono",
  "dep:thiserror",
  "dep:serde_json",
  "dep:tracing-subscriber",
  "dep:tracing-appender",
]

[dependencies]
chrono = { workspace = true, optional = true }
tracing = { workspace = true, default-features = false }
thiserror = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true, features = [
  "fmt",
  "env-filter",
] }
tracing-appender = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true, features = ["std"] }
