[package]
name = "radroots-studio-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
directories.workspace = true
radroots-studio-application = { path = "../application" }
radroots-studio-domain = { path = "../domain" }
radroots-studio-storage = { path = "../storage" }
tokio.workspace = true
uniffi.workspace = true

[dev-dependencies]
nostr.workspace = true
nostr-relay-builder.workspace = true
nostr-sdk.workspace = true
tempfile = "=3.23.0"

[lints]
workspace = true
