[package]
name = "radroots_nostr_accounts"
publish = false
version = "1.0.0-alpha.1"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Nostr account model for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_nostr_accounts"
readme = "README"

[features]
default = ["std", "file-store", "memory-vault"]
std = [
  "dep:nostr",
  "dep:serde",
  "dep:serde_json",
  "dep:radroots_identity",
  "dep:radroots_nostr_signer",
  "dep:radroots_protected_store",
  "dep:radroots_runtime",
  "dep:radroots_secret_vault",
]
file-store = ["std"]
memory-vault = ["std", "radroots_secret_vault/memory-vault"]
os-keyring = ["std", "radroots_secret_vault/os-keyring"]
nostrdb-bridge = ["std", "dep:radroots_nostrdb"]

[dependencies]
nostr = { workspace = true, optional = true }
radroots_identity = { workspace = true, optional = true, default-features = false, features = [
  "std",
  "serde",
] }
radroots_nostr_signer = { workspace = true, optional = true }
radroots_nostrdb = { workspace = true, optional = true, default-features = false, features = [
  "nostrdb",
  "giftwrap",
  "rt",
] }
radroots_protected_store = { workspace = true, optional = true, default-features = false, features = [
  "std",
] }
radroots_secret_vault = { workspace = true, optional = true, default-features = false, features = [
  "std",
] }
radroots_runtime = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
