import type { IResult, IResultList, IResultPass } from "@radroots/types-bindings";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Farm = { id: string, created_at: string, updated_at: string, name: string, area: string | null, area_unit: string | null, title: string | null, description: string | null, };

export type FarmQueryBindValues = { id: string, };

export type IFarmCreate = IFarmFields;

export type IFarmCreateResolve = IResult<Farm>;

export type IFarmDelete = IFarmFindOne;

export type IFarmDeleteResolve = IResult<string>;

export type IFarmFields = { name: string, area?: string | null, area_unit?: string | null, title?: string | null, description?: string | null, };

export type IFarmFieldsFilter = { id?: string, created_at?: string, updated_at?: string, name?: string, area?: string, area_unit?: string, title?: string, description?: string, };

export type IFarmFieldsPartial = { name?: string | null, area?: string | null, area_unit?: string | null, title?: string | null, description?: string | null, };

export type IFarmFindMany = { filter: IFarmFieldsFilter | null, };

export type IFarmFindManyResolve = IResultList<Farm>;

export type IFarmFindOne = { on: FarmQueryBindValues, };

export type IFarmFindOneResolve = IResult<Farm>;

export type IFarmLocationRelation = { farm: FarmQueryBindValues, location_gcs: LocationGcsQueryBindValues, };

export type IFarmLocationResolve = IResultPass;

export type IFarmUpdate = { on: FarmQueryBindValues, fields: IFarmFieldsPartial, };

export type IFarmUpdateResolve = IResult<Farm>;

export type ILocationGcsCreate = ILocationGcsFields;

export type ILocationGcsCreateResolve = IResult<LocationGcs>;

export type ILocationGcsDelete = ILocationGcsFindOne;

export type ILocationGcsDeleteResolve = IResult<string>;

export type ILocationGcsFields = { lat: number, lng: number, geohash: string, tag_0?: string | null, label?: string | null, area?: number | null, elevation?: number | null, soil?: string | null, climate?: string | null, gc_id?: string | null, gc_name?: string | null, gc_admin1_id?: string | null, gc_admin1_name?: string | null, gc_country_id?: string | null, gc_country_name?: string | null, };

export type ILocationGcsFieldsFilter = { id?: string, created_at?: string, updated_at?: string, lat?: number, lng?: number, geohash?: string, tag_0?: string, label?: string, area?: number, elevation?: number, soil?: string, climate?: string, gc_id?: string, gc_name?: string, gc_admin1_id?: string, gc_admin1_name?: string, gc_country_id?: string, gc_country_name?: string, };

export type ILocationGcsFieldsPartial = { lat?: number | null, lng?: number | null, geohash?: string | null, tag_0?: string | null, label?: string | null, area?: number | null, elevation?: number | null, soil?: string | null, climate?: string | null, gc_id?: string | null, gc_name?: string | null, gc_admin1_id?: string | null, gc_admin1_name?: string | null, gc_country_id?: string | null, gc_country_name?: string | null, };

export type ILocationGcsFindMany = { filter: ILocationGcsFieldsFilter | null, } | { rel: LocationGcsFindManyRel, };

export type ILocationGcsFindManyResolve = IResultList<LocationGcs>;

export type ILocationGcsFindOne = { on: LocationGcsQueryBindValues, } | { rel: LocationGcsFindManyRel, };

export type ILocationGcsFindOneResolve = IResult<LocationGcs>;

export type ILocationGcsUpdate = { on: LocationGcsQueryBindValues, fields: ILocationGcsFieldsPartial, };

export type ILocationGcsUpdateResolve = IResult<LocationGcs>;

export type ILogErrorCreate = ILogErrorFields;

export type ILogErrorCreateResolve = IResult<LogError>;

export type ILogErrorDelete = ILogErrorFindOne;

export type ILogErrorDeleteResolve = IResult<string>;

export type ILogErrorFields = { error: string, message: string, stack_trace?: string | null, cause?: string | null, app_system: string, app_version: string, nostr_pubkey: string, data?: string | null, };

export type ILogErrorFieldsFilter = { id?: string, created_at?: string, updated_at?: string, error?: string, message?: string, stack_trace?: string, cause?: string, app_system?: string, app_version?: string, nostr_pubkey?: string, data?: string, };

export type ILogErrorFieldsPartial = { error?: string | null, message?: string | null, stack_trace?: string | null, cause?: string | null, app_system?: string | null, app_version?: string | null, nostr_pubkey?: string | null, data?: string | null, };

export type ILogErrorFindMany = { filter: ILogErrorFieldsFilter | null, };

export type ILogErrorFindManyResolve = IResultList<LogError>;

export type ILogErrorFindOne = { on: LogErrorQueryBindValues, };

export type ILogErrorFindOneResolve = IResult<LogError>;

export type ILogErrorUpdate = { on: LogErrorQueryBindValues, fields: ILogErrorFieldsPartial, };

export type ILogErrorUpdateResolve = IResult<LogError>;

export type IMediaImageCreate = IMediaImageFields;

export type IMediaImageCreateResolve = IResult<MediaImage>;

export type IMediaImageDelete = IMediaImageFindOne;

export type IMediaImageDeleteResolve = IResult<string>;

export type IMediaImageFields = { file_path: string, mime_type: string, res_base: string, res_path: string, label?: string | null, description?: string | null, };

export type IMediaImageFieldsFilter = { id?: string, created_at?: string, updated_at?: string, file_path?: string, mime_type?: string, res_base?: string, res_path?: string, label?: string, description?: string, };

export type IMediaImageFieldsPartial = { file_path?: string | null, mime_type?: string | null, res_base?: string | null, res_path?: string | null, label?: string | null, description?: string | null, };

export type IMediaImageFindMany = { filter: IMediaImageFieldsFilter | null, } | { rel: MediaImageFindManyRel, };

export type IMediaImageFindManyResolve = IResultList<MediaImage>;

export type IMediaImageFindOne = { on: MediaImageQueryBindValues, };

export type IMediaImageFindOneResolve = IResult<MediaImage>;

export type IMediaImageUpdate = { on: MediaImageQueryBindValues, fields: IMediaImageFieldsPartial, };

export type IMediaImageUpdateResolve = IResult<MediaImage>;

export type INostrProfileCreate = INostrProfileFields;

export type INostrProfileCreateResolve = IResult<NostrProfile>;

export type INostrProfileDelete = INostrProfileFindOne;

export type INostrProfileDeleteResolve = IResult<string>;

export type INostrProfileFields = { public_key: string, name: string, display_name?: string | null, about?: string | null, website?: string | null, picture?: string | null, banner?: string | null, nip05?: string | null, lud06?: string | null, lud16?: string | null, };

export type INostrProfileFieldsFilter = { id?: string, created_at?: string, updated_at?: string, public_key?: string, name?: string, display_name?: string, about?: string, website?: string, picture?: string, banner?: string, nip05?: string, lud06?: string, lud16?: string, };

export type INostrProfileFieldsPartial = { public_key?: string | null, name?: string | null, display_name?: string | null, about?: string | null, website?: string | null, picture?: string | null, banner?: string | null, nip05?: string | null, lud06?: string | null, lud16?: string | null, };

export type INostrProfileFindMany = { filter: INostrProfileFieldsFilter | null, } | { rel: NostrProfileFindManyRel, };

export type INostrProfileFindManyResolve = IResultList<NostrProfile>;

export type INostrProfileFindOne = { on: NostrProfileQueryBindValues, };

export type INostrProfileFindOneResolve = IResult<NostrProfile>;

export type INostrProfileRelayRelation = { nostr_profile: NostrProfileQueryBindValues, nostr_relay: NostrRelayQueryBindValues, };

export type INostrProfileRelayResolve = IResultPass;

export type INostrProfileUpdate = { on: NostrProfileQueryBindValues, fields: INostrProfileFieldsPartial, };

export type INostrProfileUpdateResolve = IResult<NostrProfile>;

export type INostrRelayCreate = INostrRelayFields;

export type INostrRelayCreateResolve = IResult<NostrRelay>;

export type INostrRelayDelete = INostrRelayFindOne;

export type INostrRelayDeleteResolve = IResult<string>;

export type INostrRelayFields = { url: string, relay_id?: string | null, name?: string | null, description?: string | null, pubkey?: string | null, contact?: string | null, supported_nips?: string | null, software?: string | null, version?: string | null, data?: string | null, };

export type INostrRelayFieldsFilter = { id?: string, created_at?: string, updated_at?: string, url?: string, relay_id?: string, name?: string, description?: string, pubkey?: string, contact?: string, supported_nips?: string, software?: string, version?: string, data?: string, };

export type INostrRelayFieldsPartial = { url?: string | null, relay_id?: string | null, name?: string | null, description?: string | null, pubkey?: string | null, contact?: string | null, supported_nips?: string | null, software?: string | null, version?: string | null, data?: string | null, };

export type INostrRelayFindMany = { filter: INostrRelayFieldsFilter | null, } | { rel: NostrRelayFindManyRel, };

export type INostrRelayFindManyResolve = IResultList<NostrRelay>;

export type INostrRelayFindOne = { on: NostrRelayQueryBindValues, };

export type INostrRelayFindOneResolve = IResult<NostrRelay>;

export type INostrRelayUpdate = { on: NostrRelayQueryBindValues, fields: INostrRelayFieldsPartial, };

export type INostrRelayUpdateResolve = IResult<NostrRelay>;

export type ITradeProductCreate = ITradeProductFields;

export type ITradeProductCreateResolve = IResult<TradeProduct>;

export type ITradeProductDelete = ITradeProductFindOne;

export type ITradeProductDeleteResolve = IResult<string>;

export type ITradeProductFields = { key: string, category: string, title: string, summary: string, process: string, lot: string, profile: string, year: bigint, qty_amt: bigint, qty_unit: string, qty_label?: string | null, qty_avail?: number | null, price_amt: number, price_currency: string, price_qty_amt: number, price_qty_unit: string, notes?: string | null, };

export type ITradeProductFieldsFilter = { id?: string, created_at?: string, updated_at?: string, key?: string, category?: string, title?: string, summary?: string, process?: string, lot?: string, profile?: string, year?: bigint, qty_amt?: bigint, qty_unit?: string, qty_label?: string, qty_avail?: bigint, price_amt?: number, price_currency?: string, price_qty_amt?: number, price_qty_unit?: string, notes?: string, };

export type ITradeProductFieldsPartial = { key?: string | null, category?: string | null, title?: string | null, summary?: string | null, process?: string | null, lot?: string | null, profile?: string | null, year?: number | null, qty_amt?: number | null, qty_unit?: string | null, qty_label?: string | null, qty_avail?: number | null, price_amt?: number | null, price_currency?: string | null, price_qty_amt?: number | null, price_qty_unit?: string | null, notes?: string | null, };

export type ITradeProductFindMany = { filter: ITradeProductFieldsFilter | null, };

export type ITradeProductFindManyResolve = IResultList<TradeProduct>;

export type ITradeProductFindOne = { on: TradeProductQueryBindValues, };

export type ITradeProductFindOneResolve = IResult<TradeProduct>;

export type ITradeProductLocationRelation = { trade_product: TradeProductQueryBindValues, location_gcs: LocationGcsQueryBindValues, };

export type ITradeProductLocationResolve = IResultPass;

export type ITradeProductMediaRelation = { trade_product: TradeProductQueryBindValues, media_image: MediaImageQueryBindValues, };

export type ITradeProductMediaResolve = IResultPass;

export type ITradeProductUpdate = { on: TradeProductQueryBindValues, fields: ITradeProductFieldsPartial, };

export type ITradeProductUpdateResolve = IResult<TradeProduct>;

export type LocationGcs = { id: string, created_at: string, updated_at: string, lat: number, lng: number, geohash: string, tag_0: string | null, label: string | null, area: number | null, elevation: number | null, soil: string | null, climate: string | null, gc_id: string | null, gc_name: string | null, gc_admin1_id: string | null, gc_admin1_name: string | null, gc_country_id: string | null, gc_country_name: string | null, };

export type LocationGcsFindManyRel = { "on_trade_product": LocationGcsTradeProductArgs } | { "off_trade_product": LocationGcsTradeProductArgs } | { "on_farm": LocationGcsTradeProductArgs } | { "off_farm": LocationGcsTradeProductArgs };

export type LocationGcsQueryBindValues = { id: string, } | { geohash: string, };

export type LocationGcsTradeProductArgs = { id: string, };

export type LogError = { id: string, created_at: string, updated_at: string, error: string, message: string, stack_trace: string | null, cause: string | null, app_system: string, app_version: string, nostr_pubkey: string, data: string | null, };

export type LogErrorQueryBindValues = { id: string, } | { nostr_pubkey: string, };

export type MediaImage = { id: string, created_at: string, updated_at: string, file_path: string, mime_type: string, res_base: string, res_path: string, label: string | null, description: string | null, };

export type MediaImageFindManyRel = { "on_trade_product": MediaImageTradeProductArgs } | { "off_trade_product": MediaImageTradeProductArgs };

export type MediaImageQueryBindValues = { id: string, } | { file_path: string, };

export type MediaImageTradeProductArgs = { id: string, };

export type NostrProfile = { id: string, created_at: string, updated_at: string, public_key: string, name: string, display_name: string | null, about: string | null, website: string | null, picture: string | null, banner: string | null, nip05: string | null, lud06: string | null, lud16: string | null, };

export type NostrProfileFindManyRel = { "on_relay": NostrProfileRelayArgs } | { "off_relay": NostrProfileRelayArgs };

export type NostrProfileQueryBindValues = { id: string, } | { public_key: string, };

export type NostrProfileRelayArgs = { id: string, };

export type NostrRelay = { id: string, created_at: string, updated_at: string, url: string, relay_id: string | null, name: string | null, description: string | null, pubkey: string | null, contact: string | null, supported_nips: string | null, software: string | null, version: string | null, data: string | null, };

export type NostrRelayFindManyRel = { "on_profile": NostrRelayProfileArgs } | { "off_profile": NostrRelayProfileArgs };

export type NostrRelayProfileArgs = { public_key: string, };

export type NostrRelayQueryBindValues = { id: string, } | { url: string, };

export type TradeProduct = { id: string, created_at: string, updated_at: string, key: string, category: string, title: string, summary: string, process: string, lot: string, profile: string, year: bigint, qty_amt: bigint, qty_unit: string, qty_label: string | null, qty_avail: bigint | null, price_amt: number, price_currency: string, price_qty_amt: number, price_qty_unit: string, notes: string | null, };

export type TradeProductQueryBindValues = { id: string, };
