import { RadrootsCoreCurrency, RadrootsCoreDecimal, RadrootsCoreMoney, RadrootsCoreQuantityPrice, RadrootsCoreUnit } from "@radroots/core-bindings";
import { RadrootsListingDiscount, RadrootsListingQuantity, RadrootsNostrEventPtr } from "@radroots/events-bindings";

/*
 Generated by typeshare 1.13.3
*/

export interface RadrootsTradeListingSubtotal {
	price_amount: RadrootsCoreMoney;
	price_currency: RadrootsCoreCurrency;
	quantity_amount: RadrootsCoreDecimal;
	quantity_unit: RadrootsCoreUnit;
}

export interface RadrootsTradeListingTotal {
	price_amount: RadrootsCoreMoney;
	price_currency: RadrootsCoreCurrency;
	quantity_amount: RadrootsCoreDecimal;
	quantity_unit: RadrootsCoreUnit;
}

export interface TradeListingAcceptRequest {
	order_result_event_id: string;
	listing_event_id: string;
}

export interface TradeListingAcceptResult {
	listing_event_id: string;
	order_result_event_id: string;
	accepted_by: string;
}

export type TradeListingConveyanceMethod = 
	| { kind: "seller_delivery", amount: {
	window?: string;
	notes?: string;
}}
	| { kind: "buyer_pickup", amount: {
	location_hint?: string;
	by_when?: string;
}}
	| { kind: "third_party", amount: {
	provider: string;
	ref_id?: string;
	notes?: string;
}};

export interface TradeListingConveyanceRequest {
	accept_result_event_id: string;
	method: TradeListingConveyanceMethod;
}

export interface TradeListingConveyanceResult {
	verified: boolean;
	method: TradeListingConveyanceMethod;
	message?: string;
}

export interface TradeListingFulfillmentRequest {
	payment_result_event_id: string;
}

export enum TradeListingFulfillmentState {
	Preparing = "Preparing",
	Shipped = "Shipped",
	ReadyForPickup = "ReadyForPickup",
	Delivered = "Delivered",
	Canceled = "Canceled",
}

export interface TradeListingFulfillmentResult {
	state: TradeListingFulfillmentState;
	tracking?: string;
	eta?: string;
	notes?: string;
}

export interface TradeListingInvoiceRequest {
	accept_result_event_id: string;
}

export interface TradeListingInvoiceResult {
	total_sat: number;
	bolt11?: string;
	note?: string;
	expires_at?: number;
}

export interface TradeListingOrderRequestPayload {
	price: RadrootsCoreQuantityPrice;
	quantity: RadrootsListingQuantity;
}

export interface TradeListingOrderRequest {
	event: RadrootsNostrEventPtr;
	payload: TradeListingOrderRequestPayload;
}

export interface TradeListingOrderResult {
	quantity: RadrootsListingQuantity;
	price: RadrootsCoreQuantityPrice;
	discounts: RadrootsListingDiscount[];
	subtotal: RadrootsTradeListingSubtotal;
	total: RadrootsTradeListingTotal;
}

export type TradeListingPaymentProof = 
	| { kind: "zap_event", amount: {
	id: string;
}}
	| { kind: "preimage", amount: {
	hex: string;
}}
	| { kind: "txid", amount: {
	id: string;
}}
	| { kind: "external_ref", amount: {
	provider: string;
	ref_id: string;
}};

export interface TradeListingPaymentProofRequest {
	invoice_result_event_id: string;
	proof: TradeListingPaymentProof;
}

export interface TradeListingPaymentResult {
	verified: boolean;
	message?: string;
}

export interface TradeListingReceiptRequest {
	fulfillment_result_event_id: string;
	note?: string;
}

export interface TradeListingReceiptResult {
	acknowledged: boolean;
	at: number;
}

export enum TradeListingStage {
	Order = "Order",
	Accept = "Accept",
	Conveyance = "Conveyance",
	Invoice = "Invoice",
	Payment = "Payment",
	Fulfillment = "Fulfillment",
	Receipt = "Receipt",
	Cancel = "Cancel",
	Refund = "Refund",
}

export const KIND_TRADE_LISTING_ORDER_REQ: number = 5301;
export const KIND_TRADE_LISTING_ORDER_RES: number = 6301;
export const KIND_TRADE_LISTING_ACCEPT_REQ: number = 5302;
export const KIND_TRADE_LISTING_ACCEPT_RES: number = 6302;
export const KIND_TRADE_LISTING_CONVEYANCE_REQ: number = 5303;
export const KIND_TRADE_LISTING_CONVEYANCE_RES: number = 6303;
export const KIND_TRADE_LISTING_INVOICE_REQ: number = 5304;
export const KIND_TRADE_LISTING_INVOICE_RES: number = 6304;
export const KIND_TRADE_LISTING_PAYMENT_REQ: number = 5305;
export const KIND_TRADE_LISTING_PAYMENT_RES: number = 6305;
export const KIND_TRADE_LISTING_FULFILL_REQ: number = 5306;
export const KIND_TRADE_LISTING_FULFILL_RES: number = 6306;
export const KIND_TRADE_LISTING_RECEIPT_REQ: number = 5307;
export const KIND_TRADE_LISTING_RECEIPT_RES: number = 6307;
export const KIND_TRADE_LISTING_CANCEL_REQ: number = 5309;
export const KIND_TRADE_LISTING_CANCEL_RES: number = 6309;
export const KIND_TRADE_LISTING_REFUND_REQ: number = 5310;
export const KIND_TRADE_LISTING_REFUND_RES: number = 6310;
