import type { RadrootsListingDiscount, RadrootsListingQuantity, RadrootsNostrEventPtr } from "@radroots/events-bindings";

import type { RadrootsCoreCurrency, RadrootsCoreDecimal, RadrootsCoreMoney, RadrootsCoreQuantityPrice, RadrootsCoreUnit } from "@radroots/core-bindings";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RadrootsTradeListingSubtotal = { price_amount: RadrootsCoreMoney, price_currency: RadrootsCoreCurrency, quantity_amount: RadrootsCoreDecimal, quantity_unit: RadrootsCoreUnit, };

export type RadrootsTradeListingTotal = { price_amount: RadrootsCoreMoney, price_currency: RadrootsCoreCurrency, quantity_amount: RadrootsCoreDecimal, quantity_unit: RadrootsCoreUnit, };

export type TradeListingAcceptRequest = { order_result_event_id: string, listing_event_id: string, };

export type TradeListingAcceptResult = { listing_event_id: string, order_result_event_id: string, accepted_by: string, };

export type TradeListingConveyanceMethod = { "kind": "seller_delivery", "amount": { window: string | null, notes: string | null, } } | { "kind": "buyer_pickup", "amount": { location_hint: string | null, by_when: string | null, } } | { "kind": "third_party", "amount": { provider: string, ref_id: string | null, notes: string | null, } };

export type TradeListingConveyanceRequest = { accept_result_event_id: string, method: TradeListingConveyanceMethod, };

export type TradeListingConveyanceResult = { verified: boolean, method: TradeListingConveyanceMethod, message?: string | null, };

export type TradeListingFulfillmentRequest = { payment_result_event_id: string, };

export type TradeListingFulfillmentResult = { state: TradeListingFulfillmentState, tracking?: string | null, eta?: string | null, notes?: string | null, };

export type TradeListingFulfillmentState = { "kind": "preparing" } | { "kind": "shipped" } | { "kind": "ready_for_pickup" } | { "kind": "delivered" } | { "kind": "canceled" };

export type TradeListingInvoiceRequest = { accept_result_event_id: string, };

export type TradeListingInvoiceResult = { total_sat: number, bolt11?: string | null, note?: string | null, expires_at?: number | null, };

export type TradeListingOrderRequest = { event: RadrootsNostrEventPtr, payload: TradeListingOrderRequestPayload, };

export type TradeListingOrderRequestPayload = { price: RadrootsCoreQuantityPrice, quantity: RadrootsListingQuantity, };

export type TradeListingOrderResult = { quantity: RadrootsListingQuantity, price: RadrootsCoreQuantityPrice, discounts: RadrootsListingDiscount[], subtotal: RadrootsTradeListingSubtotal, total: RadrootsTradeListingTotal, };

export type TradeListingPaymentProof = { "kind": "zap_event", "amount": { id: string, } } | { "kind": "preimage", "amount": { hex: string, } } | { "kind": "txid", "amount": { id: string, } } | { "kind": "external_ref", "amount": { provider: string, ref_id: string, } };

export type TradeListingPaymentProofRequest = { invoice_result_event_id: string, proof: TradeListingPaymentProof, };

export type TradeListingPaymentResult = { verified: boolean, message?: string | null, };

export type TradeListingReceiptRequest = { fulfillment_result_event_id: string, note?: string | null, };

export type TradeListingReceiptResult = { acknowledged: boolean, at: number, };

export type TradeListingStage = { "kind": "order" } | { "kind": "accept" } | { "kind": "conveyance" } | { "kind": "invoice" } | { "kind": "payment" } | { "kind": "fulfillment" } | { "kind": "receipt" } | { "kind": "cancel" } | { "kind": "refund" };

export enum TradeListingMarker { "listing" = "listing", "payload" = "payload", "previous" = "previous", "order_result" = "order_result", "accept_result" = "accept_result", "conveyance_result" = "conveyance_result", "invoice_result" = "invoice_result", "payment_result" = "payment_result", "fulfillment_result" = "fulfillment_result", "receipt_result" = "receipt_result", "cancel_result" = "cancel_result", "refund_result" = "refund_result", "proof" = "proof" }

export enum TradeListingKind { "KIND_TRADE_LISTING_ORDER_REQ" = 5301, "KIND_TRADE_LISTING_ORDER_RES" = 6301, "KIND_TRADE_LISTING_ACCEPT_REQ" = 5302, "KIND_TRADE_LISTING_ACCEPT_RES" = 6302, "KIND_TRADE_LISTING_CONVEYANCE_REQ" = 5303, "KIND_TRADE_LISTING_CONVEYANCE_RES" = 6303, "KIND_TRADE_LISTING_INVOICE_REQ" = 5304, "KIND_TRADE_LISTING_INVOICE_RES" = 6304, "KIND_TRADE_LISTING_PAYMENT_REQ" = 5305, "KIND_TRADE_LISTING_PAYMENT_RES" = 6305, "KIND_TRADE_LISTING_FULFILL_REQ" = 5306, "KIND_TRADE_LISTING_FULFILL_RES" = 6306, "KIND_TRADE_LISTING_RECEIPT_REQ" = 5307, "KIND_TRADE_LISTING_RECEIPT_RES" = 6307, "KIND_TRADE_LISTING_CANCEL_REQ" = 5309, "KIND_TRADE_LISTING_CANCEL_RES" = 6309, "KIND_TRADE_LISTING_REFUND_REQ" = 5310, "KIND_TRADE_LISTING_REFUND_RES" = 6310 }
