// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RadrootsListing = { d_tag: string, farm: RadrootsListingFarmRef, product: RadrootsListingProduct, primary_bin_id: string, bins: Array<RadrootsListingBin>, resource_area?: RadrootsResourceAreaRef | null, plot?: RadrootsPlotRef | null, discounts?: RadrootsCoreDiscount[] | null, inventory_available?: RadrootsCoreDecimal | null, availability?: RadrootsListingAvailability | null, delivery_method?: RadrootsListingDeliveryMethod | null, location?: RadrootsListingLocation | null, images?: RadrootsListingImage[] | null, };

export type RadrootsListingAvailability = { "kind": "window", "amount": { start?: number | null, end?: number | null, } } | { "kind": "status", "amount": { status: RadrootsListingStatus, } };

export type RadrootsListingBin = { bin_id: string, quantity: RadrootsCoreQuantity, price_per_canonical_unit: RadrootsCoreQuantityPrice, display_amount?: RadrootsCoreDecimal | null, display_unit?: RadrootsCoreUnit | null, display_label?: string | null, display_price?: RadrootsCoreMoney | null, display_price_unit?: RadrootsCoreUnit | null, };

export type RadrootsListingDeliveryMethod = { "kind": "pickup" } | { "kind": "local_delivery" } | { "kind": "shipping" } | { "kind": "other", "amount": { method: string, } };

export type RadrootsListingFarmRef = { pubkey: string, d_tag: string, };

export type RadrootsListingLocation = { primary: string, city?: string | null, region?: string | null, country?: string | null, lat?: number | null, lng?: number | null, geohash?: string | null, };

export type RadrootsListingProduct = { key: string, title: string, category: string, summary?: string | null, process?: string | null, lot?: string | null, location?: string | null, profile?: string | null, year?: string | null, };

export type RadrootsListingStatus = { "kind": "active" } | { "kind": "sold" } | { "kind": "other", "amount": { value: string, } };

export type RadrootsTradeListing = { listing_id: string, listing_addr: string, seller_pubkey: string, title: string, description: string, product_type: string, primary_bin_id: string, bin_quantity: RadrootsCoreQuantity, unit: RadrootsCoreUnit, unit_price: RadrootsCoreMoney, inventory_available: RadrootsCoreDecimal, availability: RadrootsListingAvailability, location: RadrootsListingLocation, delivery_method: RadrootsListingDeliveryMethod, listing: RadrootsListing, };

export type RadrootsTradeListingSubtotal = { price_amount: RadrootsCoreMoney, price_currency: RadrootsCoreCurrency, quantity_amount: RadrootsCoreDecimal, quantity_unit: RadrootsCoreUnit, };

export type RadrootsTradeListingTotal = { price_amount: RadrootsCoreMoney, price_currency: RadrootsCoreCurrency, quantity_amount: RadrootsCoreDecimal, quantity_unit: RadrootsCoreUnit, };

export type TradeAnswer = { question_id: string, order_id?: string | null, listing_addr?: string | null, answer_text: string, };

export type TradeDiscountDecision = { "kind": "accept", "amount": { value: RadrootsCoreDiscountValue, } } | { "kind": "decline", "amount": { reason?: string | null, } };

export type TradeDiscountOffer = { discount_id: string, order_id: string, value: RadrootsCoreDiscountValue, conditions?: string | null, };

export type TradeDiscountRequest = { discount_id: string, order_id: string, value: RadrootsCoreDiscountValue, conditions?: string | null, };

export type TradeFulfillmentStatus = { "kind": "preparing" } | { "kind": "shipped" } | { "kind": "ready_for_pickup" } | { "kind": "delivered" } | { "kind": "cancelled" };

export type TradeFulfillmentUpdate = { status: TradeFulfillmentStatus, tracking?: string | null, eta?: string | null, notes?: string | null, };

export type TradeListingAcceptRequest = { order_result_event_id: string, listing_event_id: string, };

export type TradeListingAcceptResult = { listing_event_id: string, order_result_event_id: string, accepted_by: string, };

export type TradeListingCancel = { reason?: string | null, };

export type TradeListingConveyanceMethod = { "kind": "seller_delivery", "amount": { window: string | null, notes: string | null, } } | { "kind": "buyer_pickup", "amount": { location_hint: string | null, by_when: string | null, } } | { "kind": "third_party", "amount": { provider: string, ref_id: string | null, notes: string | null, } };

export type TradeListingConveyanceRequest = { accept_result_event_id: string, method: TradeListingConveyanceMethod, };

export type TradeListingConveyanceResult = { verified: boolean, method: TradeListingConveyanceMethod, message?: string | null, };

export type TradeListingDomain = "trade:listing";

export type TradeListingEnvelope<T> = { version: number, domain: TradeListingDomain, type: TradeListingMessageType, order_id?: string | null, listing_addr: string, payload: T, };

export type TradeListingFulfillmentRequest = { payment_result_event_id: string, };

export type TradeListingFulfillmentResult = { state: TradeListingFulfillmentState, tracking?: string | null, eta?: string | null, notes?: string | null, };

export type TradeListingFulfillmentState = { "kind": "preparing" } | { "kind": "shipped" } | { "kind": "ready_for_pickup" } | { "kind": "delivered" } | { "kind": "canceled" };

export type TradeListingInvoiceRequest = { accept_result_event_id: string, };

export type TradeListingInvoiceResult = { total_sat: number, bolt11?: string | null, note?: string | null, expires_at?: number | null, };

export type TradeListingMessagePayload = { "kind": "listing_validate_request", "amount": TradeListingValidateRequest } | { "kind": "listing_validate_result", "amount": TradeListingValidateResult } | { "kind": "order_request", "amount": TradeOrder } | { "kind": "order_response", "amount": TradeOrderResponse } | { "kind": "order_revision", "amount": TradeOrderRevision } | { "kind": "order_revision_accept", "amount": TradeOrderRevisionResponse } | { "kind": "order_revision_decline", "amount": TradeOrderRevisionResponse } | { "kind": "question", "amount": TradeQuestion } | { "kind": "answer", "amount": TradeAnswer } | { "kind": "discount_request", "amount": TradeDiscountRequest } | { "kind": "discount_offer", "amount": TradeDiscountOffer } | { "kind": "discount_accept", "amount": TradeDiscountDecision } | { "kind": "discount_decline", "amount": TradeDiscountDecision } | { "kind": "cancel", "amount": TradeListingCancel } | { "kind": "fulfillment_update", "amount": TradeFulfillmentUpdate } | { "kind": "receipt", "amount": TradeReceipt };

export type TradeListingMessageType = "listing_validate_request" | "listing_validate_result" | "order_request" | "order_response" | "order_revision" | "order_revision_accept" | "order_revision_decline" | "question" | "answer" | "discount_request" | "discount_offer" | "discount_accept" | "discount_decline" | "cancel" | "fulfillment_update" | "receipt";

export type TradeListingOrderRequest = { event: RadrootsNostrEventPtr, payload: TradeListingOrderRequestPayload, };

export type TradeListingOrderRequestPayload = { bin_id: string, bin_count: number, };

export type TradeListingOrderResult = { bin_id: string, bin_count: number, price: RadrootsCoreQuantityPrice, discounts: RadrootsCoreDiscount[], subtotal: RadrootsTradeListingSubtotal, total: RadrootsTradeListingTotal, };

export type TradeListingParseError = { "MissingTag": string } | { "InvalidTag": string } | { "InvalidNumber": string } | "InvalidUnit" | "InvalidCurrency" | { "InvalidJson": string } | { "InvalidDiscount": string };

export type TradeListingPaymentProof = { "kind": "zap_event", "amount": { id: string, } } | { "kind": "preimage", "amount": { hex: string, } } | { "kind": "txid", "amount": { id: string, } } | { "kind": "external_ref", "amount": { provider: string, ref_id: string, } };

export type TradeListingPaymentProofRequest = { invoice_result_event_id: string, proof: TradeListingPaymentProof, };

export type TradeListingPaymentResult = { verified: boolean, message?: string | null, };

export type TradeListingReceiptRequest = { fulfillment_result_event_id: string, note?: string | null, };

export type TradeListingReceiptResult = { acknowledged: boolean, at: number, };

export type TradeListingStage = { "kind": "order" } | { "kind": "accept" } | { "kind": "conveyance" } | { "kind": "invoice" } | { "kind": "payment" } | { "kind": "fulfillment" } | { "kind": "receipt" } | { "kind": "cancel" } | { "kind": "refund" };

export type TradeListingValidateRequest = { listing_event?: RadrootsNostrEventPtr | null, };

export type TradeListingValidateResult = { valid: boolean, errors: TradeListingValidationError[], };

export type TradeListingValidationError = { "kind": "invalid_kind", "amount": { kind: number, } } | { "kind": "missing_listing_id" } | { "kind": "listing_event_not_found", "amount": { listing_addr: string, } } | { "kind": "listing_event_fetch_failed", "amount": { listing_addr: string, } } | { "kind": "parse_error", "amount": { error: TradeListingParseError, } } | { "kind": "invalid_seller" } | { "kind": "missing_farm_profile" } | { "kind": "missing_farm_record" } | { "kind": "missing_title" } | { "kind": "missing_description" } | { "kind": "missing_product_type" } | { "kind": "missing_bins" } | { "kind": "missing_primary_bin" } | { "kind": "invalid_bin" } | { "kind": "missing_price" } | { "kind": "invalid_price" } | { "kind": "missing_inventory" } | { "kind": "invalid_inventory" } | { "kind": "missing_availability" } | { "kind": "missing_location" } | { "kind": "missing_delivery_method" };

export type TradeOrder = { order_id: string, listing_addr: string, buyer_pubkey: string, seller_pubkey: string, items: Array<TradeOrderItem>, discounts?: RadrootsCoreDiscountValue[] | null, notes?: string | null, status: TradeOrderStatus, };

export type TradeOrderChange = { "kind": "bin_count", "amount": { item_index: number, bin_count: number, } } | { "kind": "item_add", "amount": { item: TradeOrderItem, } } | { "kind": "item_remove", "amount": { item_index: number, } };

export type TradeOrderItem = { bin_id: string, bin_count: number, };

export type TradeOrderResponse = { accepted: boolean, reason?: string | null, };

export type TradeOrderRevision = { revision_id: string, order_id: string, changes: Array<TradeOrderChange>, reason?: string | null, };

export type TradeOrderRevisionResponse = { accepted: boolean, reason?: string | null, };

export type TradeOrderStatus = "draft" | "validated" | "requested" | "questioned" | "revised" | "accepted" | "declined" | "cancelled" | "fulfilled" | "completed";

export type TradeQuestion = { question_id: string, order_id?: string | null, listing_addr?: string | null, question_text: string, };

export type TradeReceipt = { acknowledged: boolean, at: bigint, note?: string | null, };

export enum TradeListingMarker { "listing" = "listing", "payload" = "payload", "previous" = "previous", "order_result" = "order_result", "accept_result" = "accept_result", "conveyance_result" = "conveyance_result", "invoice_result" = "invoice_result", "payment_result" = "payment_result", "fulfillment_result" = "fulfillment_result", "receipt_result" = "receipt_result", "cancel_result" = "cancel_result", "refund_result" = "refund_result", "proof" = "proof" }

export enum TradeListingKind { "KIND_TRADE_LISTING_ORDER_REQ" = 5301, "KIND_TRADE_LISTING_ORDER_RES" = 6301, "KIND_TRADE_LISTING_ACCEPT_REQ" = 5302, "KIND_TRADE_LISTING_ACCEPT_RES" = 6302, "KIND_TRADE_LISTING_CONVEYANCE_REQ" = 5303, "KIND_TRADE_LISTING_CONVEYANCE_RES" = 6303, "KIND_TRADE_LISTING_INVOICE_REQ" = 5304, "KIND_TRADE_LISTING_INVOICE_RES" = 6304, "KIND_TRADE_LISTING_PAYMENT_REQ" = 5305, "KIND_TRADE_LISTING_PAYMENT_RES" = 6305, "KIND_TRADE_LISTING_FULFILL_REQ" = 5306, "KIND_TRADE_LISTING_FULFILL_RES" = 6306, "KIND_TRADE_LISTING_RECEIPT_REQ" = 5307, "KIND_TRADE_LISTING_RECEIPT_RES" = 6307, "KIND_TRADE_LISTING_CANCEL_REQ" = 5309, "KIND_TRADE_LISTING_CANCEL_RES" = 6309, "KIND_TRADE_LISTING_REFUND_REQ" = 5310, "KIND_TRADE_LISTING_REFUND_RES" = 6310 }

export enum TradeListingDvmKind { "KIND_TRADE_LISTING_VALIDATE_REQ" = 5321, "KIND_TRADE_LISTING_VALIDATE_RES" = 6321, "KIND_TRADE_LISTING_ORDER_REQ" = 5322, "KIND_TRADE_LISTING_ORDER_RES" = 6322, "KIND_TRADE_LISTING_ORDER_REVISION_REQ" = 5323, "KIND_TRADE_LISTING_ORDER_REVISION_RES" = 6323, "KIND_TRADE_LISTING_QUESTION_REQ" = 5324, "KIND_TRADE_LISTING_ANSWER_RES" = 6324, "KIND_TRADE_LISTING_DISCOUNT_REQ" = 5325, "KIND_TRADE_LISTING_DISCOUNT_OFFER_RES" = 6325, "KIND_TRADE_LISTING_DISCOUNT_ACCEPT_REQ" = 5326, "KIND_TRADE_LISTING_DISCOUNT_DECLINE_REQ" = 5327, "KIND_TRADE_LISTING_CANCEL_REQ" = 5328, "KIND_TRADE_LISTING_FULFILLMENT_UPDATE_REQ" = 5329, "KIND_TRADE_LISTING_RECEIPT_REQ" = 5330 }
