use super::CommentOperationExpectation;

pub(super) const COMMENT_CONFORMANCE_VECTOR_RELATIVE: &str =
    "contracts/conformance/vectors/comment/verified_profile.v1.json";

pub(super) const REQUIRED_COMMENT_PUBLIC_TYPES: [&str; 26] = [
    "RadrootsNip01EventWireParts",
    "RadrootsEventEnvelope",
    "RadrootsSignatureVerifiedEvent",
    "RadrootsNostrRelayHint",
    "RadrootsNip22CommentError",
    "RadrootsNip22CommentRootKind",
    "RadrootsNip22EventRootReference",
    "RadrootsNip22AddressRootReference",
    "RadrootsNip22CommentParentReference",
    "RadrootsNip22CommentRoot",
    "RadrootsNip22CommentPosition",
    "RadrootsAuthoredNip22Comment",
    "RadrootsNip22CommentDiagnostic",
    "RadrootsInboundNip22Participant",
    "RadrootsInboundNip22EventRoot",
    "RadrootsInboundNip22AddressRoot",
    "RadrootsInboundNip22CommentRoot",
    "RadrootsInboundNip22CommentParent",
    "RadrootsInboundNip22CurrentRevision",
    "RadrootsInboundNip22TopLevelEventReference",
    "RadrootsInboundNip22TopLevelAddressReference",
    "RadrootsInboundNip22CommentPosition",
    "RadrootsInboundNip22CommentProjection",
    "RadrootsNip22CommentProjectionError",
    "RadrootsAdmittedNip22CommentEvent",
    "RadrootsNip22CommentAdmissionError",
];

pub(super) const COMMENT_OPERATION_EXPECTATIONS: [CommentOperationExpectation; 3] = [
    CommentOperationExpectation {
        key: "social_comment_build_authored_draft",
        id: "social.comment.build_authored_draft",
        inputs: &["RadrootsAuthoredNip22Comment"],
        outputs: &["RadrootsNip01EventWireParts"],
        error_class: "encode_error",
        signing: "none",
        rust_modules: &[
            "crates/event/src/comment.rs",
            "crates/event/src/relay_hint.rs",
            "crates/event_codec/src/comment/authored.rs",
        ],
        rust_types: &[
            "radroots_event::comment::RadrootsAuthoredNip22Comment",
            "radroots_event::comment::RadrootsNip22AddressRootReference",
            "radroots_event::comment::RadrootsNip22CommentError",
            "radroots_event::comment::RadrootsNip22CommentParentReference",
            "radroots_event::comment::RadrootsNip22CommentPosition",
            "radroots_event::comment::RadrootsNip22CommentRoot",
            "radroots_event::comment::RadrootsNip22CommentRootKind",
            "radroots_event::comment::RadrootsNip22EventRootReference",
            "radroots_event::relay_hint::RadrootsNostrRelayHint",
            "radroots_event::wire::RadrootsNip01EventWireParts",
        ],
        case_kinds: &[
            "social.comment.build_authored_draft.valid",
            "social.comment.build_authored_draft.invalid",
        ],
    },
    CommentOperationExpectation {
        key: "social_comment_project_verified_event",
        id: "social.comment.project_verified_event",
        inputs: &["RadrootsSignatureVerifiedEvent"],
        outputs: &["RadrootsInboundNip22CommentProjection"],
        error_class: "parse_error",
        signing: "none",
        rust_modules: &[
            "crates/event_codec/src/comment/inbound.rs",
            "crates/event_codec/src/verification.rs",
        ],
        rust_types: &[
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22AddressRoot",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22CommentParent",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22CommentPosition",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22CommentProjection",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22CommentRoot",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22CurrentRevision",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22EventRoot",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22Participant",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22TopLevelAddressReference",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22TopLevelEventReference",
            "radroots_event_codec::comment::inbound::RadrootsNip22CommentDiagnostic",
            "radroots_event_codec::comment::inbound::RadrootsNip22CommentProjectionError",
            "radroots_event_codec::verification::RadrootsSignatureVerifiedEvent",
        ],
        case_kinds: &[
            "social.comment.project_verified_event.valid",
            "social.comment.project_verified_event.invalid",
        ],
    },
    CommentOperationExpectation {
        key: "social_comment_verify_and_admit_event",
        id: "social.comment.verify_and_admit_event",
        inputs: &["RadrootsEventEnvelope"],
        outputs: &["RadrootsAdmittedNip22CommentEvent"],
        error_class: "admission_error",
        signing: "nip01",
        rust_modules: &[
            "crates/event_codec/src/comment/admission.rs",
            "crates/event_codec/src/comment/inbound.rs",
            "crates/event_codec/src/verification.rs",
        ],
        rust_types: &[
            "radroots_event::RadrootsEventEnvelope",
            "radroots_event_codec::comment::admission::RadrootsAdmittedNip22CommentEvent",
            "radroots_event_codec::comment::admission::RadrootsNip22CommentAdmissionError",
            "radroots_event_codec::comment::inbound::RadrootsInboundNip22CommentProjection",
            "radroots_event_codec::comment::inbound::RadrootsNip22CommentProjectionError",
            "radroots_event_codec::verification::RadrootsSignatureVerifiedEvent",
        ],
        case_kinds: &[
            "social.comment.verify_and_admit_event.valid",
            "social.comment.verify_and_admit_event.invalid",
        ],
    },
];

pub(super) const COMMENT_CASE_KINDS: [&str; 6] = [
    "social.comment.build_authored_draft.valid",
    "social.comment.build_authored_draft.invalid",
    "social.comment.project_verified_event.valid",
    "social.comment.project_verified_event.invalid",
    "social.comment.verify_and_admit_event.valid",
    "social.comment.verify_and_admit_event.invalid",
];

pub(super) const COMMENT_VECTOR_EXPECTATIONS: [(&str, &str); 114] = [
    (
        "authored_top_event_listing",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_top_event_date",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_top_event_time",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_top_address_listing",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_top_address_date",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_top_address_time",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_nested_event_listing",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_nested_event_date",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_nested_event_time",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_nested_address_listing",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_nested_address_date",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_nested_address_time",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_blank_content",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_kind_one_root",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_kind_comment_root",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_invalid_event_id",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_invalid_author",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_invalid_coordinate",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_invalid_current_revision",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_parent_matches_root",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_relay_uppercase_scheme",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_relay_zero_port",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_relay_lower_percent",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_escaped_wire_overflow",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "project_signed_top_event",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_signed_top_address",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_signed_nested_event",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_signed_nested_address",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_unordered_top_event",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_unordered_top_address",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_supplemental_unknown_tag",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_supplemental_q_tag",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_additional_participant",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_duplicate_participant",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_malformed_participant",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_invalid_root_relay",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_invalid_root_participant_relay",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_invalid_parent_relay",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_malformed_root_author_hint",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_malformed_parent_author_hint",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_missing_nested_author_hint",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_distinct_relay_hints",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_invalid_address_root_relay",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_invalid_address_reference_relay",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_invalid_revision_relay",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_invalid_participant_relay",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_malformed_participant_shape",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_tag_count_exact",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_tag_element_count_exact",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_wrong_kind",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_blank_content",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_mixed_root",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_duplicate_root",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_duplicate_K",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_missing_P",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_unsupported_K",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_padded_K",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_plus_K",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_address_K_mismatch",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_invalid_P",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_address_P_mismatch",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_top_reference_mismatch",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_top_hint_mismatch",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_nested_parent_matches_root",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_nested_missing_p",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_nested_ambiguous_p",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_address_missing_a",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_revision_author_extra",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_event_reference_extra",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_count_overflow",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_element_count_overflow",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_external_root_form",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_external_parent_form",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "admit_signed_top_event",
        "social.comment.verify_and_admit_event.valid",
    ),
    (
        "admit_signed_top_address",
        "social.comment.verify_and_admit_event.valid",
    ),
    (
        "admit_signed_nested_event",
        "social.comment.verify_and_admit_event.valid",
    ),
    (
        "admit_signed_nested_address",
        "social.comment.verify_and_admit_event.valid",
    ),
    (
        "admit_invalid_signature",
        "social.comment.verify_and_admit_event.invalid",
    ),
    (
        "admit_id_mismatch",
        "social.comment.verify_and_admit_event.invalid",
    ),
    (
        "admit_invalid_shape",
        "social.comment.verify_and_admit_event.invalid",
    ),
    (
        "admit_wrong_kind",
        "social.comment.verify_and_admit_event.invalid",
    ),
    (
        "nip22_comment_u001c_is_content",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "comment_nbsp_blank_content",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "inbound_nip22_u001c_is_content",
        "social.comment.project_verified_event.valid",
    ),
    (
        "inbound_comment_nbsp_blank_content",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "authored_content_bytes_exact",
        "social.comment.build_authored_draft.valid",
    ),
    (
        "authored_content_bytes_overflow",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "project_content_bytes_exact",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_content_bytes_overflow",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_element_bytes_exact",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_tag_element_bytes_overflow",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_bytes_exact",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_tag_bytes_overflow",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_event_wire_bytes_exact",
        "social.comment.project_verified_event.valid",
    ),
    (
        "project_event_wire_bytes_overflow",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_root_event_id_invalid",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_root_coordinate_invalid",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_parent_kind_missing",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_parent_kind_noncanonical",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_parent_reference_shape",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_parent_event_id_invalid",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_parent_coordinate_invalid",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_revision_missing",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_revision_event_id_invalid",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_parent_author_mismatch",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_content_budget_precedes_missing_authority",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_count_budget_precedes_missing_authority",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_element_count_budget_precedes_missing_authority",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_element_budget_precedes_missing_authority",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_tag_bytes_budget_precedes_missing_authority",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "project_event_wire_budget_precedes_missing_authority",
        "social.comment.project_verified_event.invalid",
    ),
    (
        "authored_invalid_parent_event_id",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_invalid_parent_author",
        "social.comment.build_authored_draft.invalid",
    ),
    (
        "authored_relay_element_bytes_overflow",
        "social.comment.build_authored_draft.invalid",
    ),
];
