[package]
name = "radroots_transport_publish_protocol"
publish = false
version = "0.1.0-alpha"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license = "MIT OR Apache-2.0"
description = "Transport publish protocol for Radrootsd"
repository.workspace = true
homepage.workspace = true
readme = "README"

[features]
default = ["std", "serde"]
std = []
serde = ["dep:serde", "radroots_transport/serde"]

[dependencies]
radroots_transport = { workspace = true, default-features = false }
serde = { workspace = true, optional = true, features = ["alloc", "derive"] }

[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }
