[package]
edition = "2021"
name = "libsqlite3-sys"
version = "0.37.0"
authors = ["The rusqlite developers"]
build = "build.rs"
links = "sqlite3"
exclude = ["**/*.sh"]
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
description = "Native bindings to the libsqlite3 library"
keywords = [
    "sqlite",
    "ffi",
]
categories = ["external-ffi-bindings"]
license = "MIT"
repository = "https://github.com/rusqlite/rusqlite"
publish = false

[package.metadata.radroots]
sqlite_version = "3.53.3"
sqlite_version_number = 3053003
sqlite_source_id = "2026-06-26 20:14:12 d4c0e51e4aeb96955b99185ab9cde75c339e2c29c3f3f12428d364a10d782c62"
sqlite_amalgamation_sha3_256 = "d45c688a8cb23f68611a894a756a12d7eb6ab6e9e2468ca70adbeab3808b5ab9"

[features]
buildtime_bindgen = [
    "bindgen",
    "pkg-config",
    "vcpkg",
]
bundled = [
    "cc",
    "bundled_bindings",
]
bundled-windows = [
    "cc",
    "bundled_bindings",
]
bundled_bindings = []
column_metadata = []
default = []
in_gecko = []
loadable_extension = [
    "prettyplease",
    "quote",
    "syn",
]
min_sqlite_version_3_34_1 = [
    "pkg-config",
    "vcpkg",
]
preupdate_hook = ["buildtime_bindgen"]
session = [
    "preupdate_hook",
    "buildtime_bindgen",
]
unlock_notify = []
wasm32-wasi-vfs = []
with-asan = []

[lib]
name = "libsqlite3_sys"
path = "src/lib.rs"

[build-dependencies.bindgen]
version = "0.72"
features = ["runtime"]
optional = true
default-features = false

[build-dependencies.cc]
version = "1.2.27"
optional = true

[build-dependencies.pkg-config]
version = "0.3.19"
optional = true

[build-dependencies.prettyplease]
version = "0.2.20"
optional = true

[build-dependencies.quote]
version = "1.0.36"
optional = true
default-features = false

[build-dependencies.syn]
version = "2.0.89"
features = [
    "full",
    "extra-traits",
    "visit-mut",
]
optional = true

[build-dependencies.vcpkg]
version = "0.2.15"
optional = true
