// Generated by ts-to-zod
import { z } from "zod";

export const listingOrderQuantitySchema = z.object({
  amount: z.number(),
  unit: z.string(),
  label: z.string(),
  count: z.number(),
});

export const listingOrderPriceSchema = z.object({
  amount: z.number(),
  currency: z.string(),
  quantity_amount: z.number(),
  quantity_unit: z.string(),
});

export const listingOrderDiscountSchema = z.object({
  discount_type: z.string(),
  threshold: z.number().optional(),
  threshold_unit: z.string().optional(),
  discount_per_unit: z.number().optional(),
  discount_unit: z.string().optional(),
  discount_percent: z.number().optional(),
  discount_amount: z.number(),
  currency: z.string(),
});

export const listingOrderSubtotalSchema = z.object({
  price_amount: z.number(),
  price_currency: z.string(),
  quantity_amount: z.number(),
  quantity_unit: z.string(),
});

export const listingOrderTotalSchema = z.object({
  price_amount: z.number(),
  price_currency: z.string(),
  quantity_amount: z.number(),
  quantity_unit: z.string(),
});

export const listingOrderSchema = z.object({
  quantity: listingOrderQuantitySchema,
  price: listingOrderPriceSchema,
  discounts: z.array(listingOrderDiscountSchema),
  subtotal: listingOrderSubtotalSchema,
  total: listingOrderTotalSchema,
});

export const listingOrderRequestEventSchema = z.object({
  id: z.string(),
});

export const listingOrderRequestPriceSchema = z.object({
  amount: z.number(),
  currency: z.string(),
  quantity_amount: z.number(),
  quantity_unit: z.string(),
});

export const listingOrderRequestQuantitySchema = z.object({
  amount: z.number(),
  unit: z.string(),
  label: z.string(),
  count: z.number(),
});

export const listingOrderRequestPayloadSchema = z.object({
  price: listingOrderRequestPriceSchema,
  quantity: listingOrderRequestQuantitySchema,
});

export const listingOrderRequestSchema = z.object({
  event: listingOrderRequestEventSchema,
  payload: listingOrderRequestPayloadSchema,
});
