/*
 Generated by typeshare 1.13.2
*/

export interface ListingOrderQuantity {
	amount: number;
	unit: string;
	label: string;
	count: number;
}

export interface ListingOrderPrice {
	amount: number;
	currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrderDiscount {
	discount_type: string;
	threshold?: number;
	threshold_unit?: string;
	discount_per_unit?: number;
	discount_unit?: string;
	discount_percent?: number;
	discount_amount: number;
	currency: string;
}

export interface ListingOrderSubtotal {
	price_amount: number;
	price_currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrderTotal {
	price_amount: number;
	price_currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrder {
	quantity: ListingOrderQuantity;
	price: ListingOrderPrice;
	discounts: ListingOrderDiscount[];
	subtotal: ListingOrderSubtotal;
	total: ListingOrderTotal;
}

export interface ListingOrderRequestEvent {
	id: string;
}

export interface ListingOrderRequestPrice {
	amount: number;
	currency: string;
	quantity_amount: number;
	quantity_unit: string;
}

export interface ListingOrderRequestQuantity {
	amount: number;
	unit: string;
	label: string;
	count: number;
}

export interface ListingOrderRequestPayload {
	price: ListingOrderRequestPrice;
	quantity: ListingOrderRequestQuantity;
}

export interface ListingOrderRequest {
	event: ListingOrderRequestEvent;
	payload: ListingOrderRequestPayload;
}

