/*
 Generated by typeshare 1.13.3
*/

export type RadrootsCoreCurrency = [number, number, number];

export type RadrootsCoreDecimal = number;

export interface RadrootsCoreMoney {
	amount: RadrootsCoreDecimal;
	currency: RadrootsCoreCurrency;
}

export interface RadrootsCorePercent {
	value: RadrootsCoreDecimal;
}

export enum RadrootsCoreUnit {
	Each = "Each",
	MassKg = "MassKg",
	MassG = "MassG",
	MassOz = "MassOz",
	MassLb = "MassLb",
	VolumeL = "VolumeL",
	VolumeMl = "VolumeMl",
}

export interface RadrootsCoreQuantity {
	amount: RadrootsCoreDecimal;
	unit: RadrootsCoreUnit;
	label?: string;
}

export interface RadrootsCoreQuantityPrice {
	amount: RadrootsCoreMoney;
	quantity: RadrootsCoreQuantity;
}

export type RadrootsCoreDiscount = 
	| { kind: "quantity_threshold", amount: {
	ref_key?: string;
	threshold: RadrootsCoreQuantity;
	value: RadrootsCoreMoney;
}}
	| { kind: "mass_threshold", amount: {
	threshold: RadrootsCoreQuantity;
	value: RadrootsCoreMoney;
}}
	| { kind: "subtotal_threshold", amount: {
	threshold: RadrootsCoreMoney;
	value: RadrootsCoreDiscountValue;
}}
	| { kind: "total_threshold", amount: {
	total_min: RadrootsCoreMoney;
	value: RadrootsCorePercent;
}};

export type RadrootsCoreDiscountValue = 
	| { kind: "money", amount: RadrootsCoreMoney }
	| { kind: "percent", amount: RadrootsCorePercent };

