[package]
name = "radroots_authority"
publish = false
version = "1.0.0-alpha.1"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Authority model for Radroots"
repository.workspace = true
homepage.workspace = true

[features]
default = ["std"]
std = ["radroots_event/std"]
local_signer = [
  "std",
  "dep:radroots_nostr",
  "radroots_nostr/events",
  "radroots_nostr/std",
]

[dependencies]
radroots_event = { workspace = true, default-features = false, features = [
  "signature",
] }
radroots_nostr = { workspace = true, optional = true, default-features = false }

[dev-dependencies]
radroots_nostr = { workspace = true, default-features = false, features = [
  "events",
  "std",
] }
serde_json = { workspace = true, default-features = false, features = [
  "alloc",
] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
