//! Stable, secret-safe storage failures.

use core::fmt;

/// Backend-neutral storage failure.
#[non_exhaustive]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Error {
    InvalidSourceGeneration,
    InvalidEventSequence,
    InvalidEventQueryLimit,
    EmptyEventQueryIds,
    TooManyEventQueryIds,
    DuplicateEventQueryId,
    AdmissionEventMismatch,
    AdmissionRegression,
    EventConflict,
    EventPageLimitExceeded,
    CursorGenerationMismatch,
    SourceGenerationChanged,
    EventNotFound,
    CorruptStoredEvent,
    BackendUnavailable,
    InvalidOperationInstanceId,
    InvalidIdempotencyKey,
    InvalidOperationTimestamp,
    InvalidJournalRevision,
    InvalidRecoveryAttempt,
    InvalidRecoveryDeadline,
    InvalidJournalQueryLimit,
    IdempotencyConflict,
    OperationNotFound,
    OperationIdentityMismatch,
    JournalRevisionConflict,
    InvalidJournalTransition,
    JournalOperationCommitted,
    CorruptJournalRecord,
    InvalidOutboxItemId,
    InvalidOutboxRevision,
    InvalidOutboxTimestamp,
    InvalidOutboxLease,
    InvalidOutboxLeaseOwner,
    InvalidOutboxClaimLimit,
    InvalidDeliveryAttempt,
    InvalidDeliveryEvidence,
    OutboxItemNotFound,
    OutboxItemNotReady,
    OutboxItemTerminal,
    OutboxPlanConflict,
    OutboxLeaseConflict,
    OutboxLeaseExpired,
    OutboxRevisionConflict,
    CorruptOutboxRecord,
    InvalidProjectionId,
    InvalidProjectionGeneration,
    InvalidProjectionRevision,
    InvalidProjectionTimestamp,
    InvalidProjectionInvalidation,
    ProjectionCheckpointMismatch,
    ProjectionCheckpointRegression,
    ProjectionRevisionConflict,
    InvalidRebuildTicketId,
    InvalidRebuildTransition,
    RebuildTicketTerminal,
    InvalidEventIndexShardId,
    InvalidEventIndexRange,
    InvalidEventIndexArtifactPath,
    InvalidEventIndexShardCount,
    InvalidEventIndexTimestamp,
    InvalidEventIndexManifest,
    InvalidEventIndexCursor,
    InvalidEventIndexCheckpoint,
    DuplicateEventIndexShard,
    CorruptProjectionRecord,
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::InvalidSourceGeneration => "storage source generation is invalid",
            Self::InvalidEventSequence => "storage event sequence is invalid",
            Self::InvalidEventQueryLimit => "storage event query limit is invalid",
            Self::EmptyEventQueryIds => "storage event id query is empty",
            Self::TooManyEventQueryIds => "storage event id query exceeds its limit",
            Self::DuplicateEventQueryId => "storage event id query contains a duplicate",
            Self::AdmissionEventMismatch => "storage admission event identities do not match",
            Self::AdmissionRegression => "storage admission cannot regress event state",
            Self::EventConflict => "storage contains conflicting data for the event id",
            Self::EventPageLimitExceeded => "storage event page exceeds its requested limit",
            Self::CursorGenerationMismatch => "storage cursor belongs to another source generation",
            Self::SourceGenerationChanged => "storage source generation changed",
            Self::EventNotFound => "storage event was not found",
            Self::CorruptStoredEvent => "storage event data is corrupt",
            Self::BackendUnavailable => "storage backend is unavailable",
            Self::InvalidOperationInstanceId => "storage operation instance id is invalid",
            Self::InvalidIdempotencyKey => "storage idempotency key is invalid",
            Self::InvalidOperationTimestamp => "storage operation timestamp is invalid",
            Self::InvalidJournalRevision => "storage journal revision is invalid",
            Self::InvalidRecoveryAttempt => "storage recovery attempt is invalid",
            Self::InvalidRecoveryDeadline => "storage recovery deadline is invalid",
            Self::InvalidJournalQueryLimit => "storage journal query limit is invalid",
            Self::IdempotencyConflict => "storage idempotency key conflicts with prior input",
            Self::OperationNotFound => "storage journal operation was not found",
            Self::OperationIdentityMismatch => "storage journal operation identity does not match",
            Self::JournalRevisionConflict => {
                "storage journal revision conflicts with durable state"
            }
            Self::InvalidJournalTransition => "storage journal transition is invalid",
            Self::JournalOperationCommitted => "storage journal operation is already committed",
            Self::CorruptJournalRecord => "storage journal record is corrupt",
            Self::InvalidOutboxItemId => "storage outbox item id is invalid",
            Self::InvalidOutboxRevision => "storage outbox revision is invalid",
            Self::InvalidOutboxTimestamp => "storage outbox timestamp is invalid",
            Self::InvalidOutboxLease => "storage outbox lease is invalid",
            Self::InvalidOutboxLeaseOwner => "storage outbox lease owner is invalid",
            Self::InvalidOutboxClaimLimit => "storage outbox claim limit is invalid",
            Self::InvalidDeliveryAttempt => "storage delivery attempt is invalid",
            Self::InvalidDeliveryEvidence => "storage delivery evidence is invalid",
            Self::OutboxItemNotFound => "storage outbox item was not found",
            Self::OutboxItemNotReady => "storage outbox item is not ready",
            Self::OutboxItemTerminal => "storage outbox item is terminal",
            Self::OutboxPlanConflict => "storage outbox plan conflicts with durable state",
            Self::OutboxLeaseConflict => "storage outbox lease conflicts with durable state",
            Self::OutboxLeaseExpired => "storage outbox lease expired",
            Self::OutboxRevisionConflict => "storage outbox revision conflicts with durable state",
            Self::CorruptOutboxRecord => "storage outbox record is corrupt",
            Self::InvalidProjectionId => "storage projection id is invalid",
            Self::InvalidProjectionGeneration => "storage projection generation is invalid",
            Self::InvalidProjectionRevision => "storage projection revision is invalid",
            Self::InvalidProjectionTimestamp => "storage projection timestamp is invalid",
            Self::InvalidProjectionInvalidation => "storage projection invalidation is invalid",
            Self::ProjectionCheckpointMismatch => {
                "storage projection checkpoint identity does not match"
            }
            Self::ProjectionCheckpointRegression => "storage projection checkpoint regressed",
            Self::ProjectionRevisionConflict => {
                "storage projection revision conflicts with durable state"
            }
            Self::InvalidRebuildTicketId => "storage projection rebuild ticket id is invalid",
            Self::InvalidRebuildTransition => "storage projection rebuild transition is invalid",
            Self::RebuildTicketTerminal => "storage projection rebuild ticket is terminal",
            Self::InvalidEventIndexShardId => "storage event-index shard id is invalid",
            Self::InvalidEventIndexRange => "storage event-index id range is invalid",
            Self::InvalidEventIndexArtifactPath => "storage event-index artifact path is invalid",
            Self::InvalidEventIndexShardCount => "storage event-index shard count is invalid",
            Self::InvalidEventIndexTimestamp => "storage event-index timestamp is invalid",
            Self::InvalidEventIndexManifest => "storage event-index manifest is invalid",
            Self::InvalidEventIndexCursor => "storage event-index cursor is invalid",
            Self::InvalidEventIndexCheckpoint => "storage event-index checkpoint is invalid",
            Self::DuplicateEventIndexShard => "storage event-index shard is duplicated",
            Self::CorruptProjectionRecord => "storage projection record is corrupt",
        })
    }
}

impl std::error::Error for Error {}
