//! Stable, secret-safe storage failures.

use core::fmt;

/// Backend-neutral storage failure.
#[non_exhaustive]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Error {
    InvalidAuthoredOperation,
    InvalidAuthoredArtifact,
    InvalidAuthoredTransition,
    InvalidAuthoredDeliveryPlan,
    DeliveryPlanClaimConflict,
    DeliveryAttemptOverflow,
    InvalidWorkClaim,
    InvalidWorkFailure,
    InvalidRetrySchedule,
    InvalidSourceGeneration,
    InvalidEventSequence,
    InvalidEventQueryLimit,
    EmptyEventQueryIds,
    TooManyEventQueryIds,
    DuplicateEventQueryId,
    AdmissionEventMismatch,
    AdmissionRegression,
    EventConflict,
    EventPageLimitExceeded,
    CursorGenerationMismatch,
    SourceGenerationChanged,
    EventNotFound,
    CorruptStoredEvent,
    BackendUnavailable,
    InvalidOperationInstanceId,
    InvalidIdempotencyKey,
    InvalidOperationTimestamp,
    InvalidJournalRevision,
    InvalidRecoveryAttempt,
    InvalidRecoveryDeadline,
    InvalidJournalQueryLimit,
    IdempotencyConflict,
    OperationNotFound,
    OperationIdentityMismatch,
    JournalRevisionConflict,
    InvalidJournalTransition,
    JournalOperationCommitted,
    CorruptJournalRecord,
    InvalidOutboxItemId,
    InvalidOutboxRevision,
    InvalidOutboxTimestamp,
    InvalidOutboxLease,
    InvalidOutboxLeaseOwner,
    InvalidOutboxClaimLimit,
    InvalidDeliveryAttempt,
    InvalidDeliveryEvidence,
    OutboxItemNotFound,
    OutboxItemNotReady,
    OutboxItemTerminal,
    OutboxPlanConflict,
    OutboxLeaseConflict,
    OutboxLeaseExpired,
    OutboxRevisionConflict,
    CorruptOutboxRecord,
    InvalidProjectionId,
    InvalidProjectionGeneration,
    InvalidProjectionRevision,
    InvalidProjectionTimestamp,
    InvalidProjectionInvalidation,
    ProjectionCheckpointMismatch,
    ProjectionCheckpointRegression,
    ProjectionRevisionConflict,
    InvalidRebuildTicketId,
    InvalidRebuildTransition,
    RebuildTicketTerminal,
    InvalidEventIndexShardId,
    InvalidEventIndexRange,
    InvalidEventIndexArtifactPath,
    InvalidEventIndexShardCount,
    InvalidEventIndexTimestamp,
    InvalidEventIndexManifest,
    InvalidEventIndexCursor,
    InvalidEventIndexCheckpoint,
    DuplicateEventIndexShard,
    CorruptProjectionRecord,
    InvalidProjectionDocument,
    InvalidProjectionSnapshot,
    CorruptProjectionDocument,
    InvalidPrivateArtifactId,
    InvalidPrivateArtifactKind,
    InvalidPrivateArtifactSchema,
    InvalidPrivateArtifactSecretReference,
    InvalidPrivateArtifactRetention,
    InvalidPrivateArtifactRevision,
    InvalidPrivateArtifactResealId,
    InvalidPrivateArtifactResealRequest,
    InvalidPrivateArtifactTimestamp,
    InvalidPrivateArtifactMetadata,
    PrivateArtifactNotFound,
    PrivateArtifactConflict,
    PrivateArtifactRevisionConflict,
    PrivateArtifactResealConflict,
    PrivateArtifactPersistenceIndeterminate,
    PrivateArtifactRetentionActive,
    PrivateArtifactNotExpired,
    PrivateArtifactTombstoned,
    InvalidExpiredArtifactQueryLimit,
    CorruptPrivateArtifactMetadata,
    InvalidBackupId,
    InvalidBackupVersion,
    InvalidBackupTimestamp,
    InvalidBackupMemberPath,
    InvalidBackupMemberLength,
    InvalidBackupManifest,
    DuplicateBackupMember,
    BackupSecretPolicyViolation,
    BackupManifestPlanMismatch,
    InvalidBackupTransition,
    InvalidRestoreTimestamp,
    InvalidRestoreTransition,
    RestoreMemberVerificationFailed,
    InvalidReliabilityRevision,
    ReliabilityRevisionConflict,
    ReliabilityOperationTerminal,
    CorruptReliabilityOperation,
    InvalidIntegrityStatus,
    InvalidStorageStatus,
    InvalidAtomicCommitId,
    InvalidAtomicCommitTimestamp,
    AtomicCommitConflict,
    AtomicWorkflowMismatch,
    AtomicCommitFailed,
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::InvalidAuthoredOperation => "storage authored operation is invalid",
            Self::InvalidAuthoredArtifact => "storage authored artifact is invalid",
            Self::InvalidAuthoredTransition => "storage authored transition is invalid",
            Self::InvalidAuthoredDeliveryPlan => "storage authored delivery plan is invalid",
            Self::DeliveryPlanClaimConflict => "storage delivery plan claim conflicts",
            Self::DeliveryAttemptOverflow => "storage delivery attempt counter overflowed",
            Self::InvalidWorkClaim => "storage authored work claim is invalid",
            Self::InvalidWorkFailure => "storage authored work failure is invalid",
            Self::InvalidRetrySchedule => "storage authored retry schedule is invalid",
            Self::InvalidSourceGeneration => "storage source generation is invalid",
            Self::InvalidEventSequence => "storage event sequence is invalid",
            Self::InvalidEventQueryLimit => "storage event query limit is invalid",
            Self::EmptyEventQueryIds => "storage event id query is empty",
            Self::TooManyEventQueryIds => "storage event id query exceeds its limit",
            Self::DuplicateEventQueryId => "storage event id query contains a duplicate",
            Self::AdmissionEventMismatch => "storage admission event identities do not match",
            Self::AdmissionRegression => "storage admission cannot regress event state",
            Self::EventConflict => "storage contains conflicting data for the event id",
            Self::EventPageLimitExceeded => "storage event page exceeds its requested limit",
            Self::CursorGenerationMismatch => "storage cursor belongs to another source generation",
            Self::SourceGenerationChanged => "storage source generation changed",
            Self::EventNotFound => "storage event was not found",
            Self::CorruptStoredEvent => "storage event data is corrupt",
            Self::BackendUnavailable => "storage backend is unavailable",
            Self::InvalidOperationInstanceId => "storage operation instance id is invalid",
            Self::InvalidIdempotencyKey => "storage idempotency key is invalid",
            Self::InvalidOperationTimestamp => "storage operation timestamp is invalid",
            Self::InvalidJournalRevision => "storage journal revision is invalid",
            Self::InvalidRecoveryAttempt => "storage recovery attempt is invalid",
            Self::InvalidRecoveryDeadline => "storage recovery deadline is invalid",
            Self::InvalidJournalQueryLimit => "storage journal query limit is invalid",
            Self::IdempotencyConflict => "storage idempotency key conflicts with prior input",
            Self::OperationNotFound => "storage journal operation was not found",
            Self::OperationIdentityMismatch => "storage journal operation identity does not match",
            Self::JournalRevisionConflict => {
                "storage journal revision conflicts with durable state"
            }
            Self::InvalidJournalTransition => "storage journal transition is invalid",
            Self::JournalOperationCommitted => "storage journal operation is already committed",
            Self::CorruptJournalRecord => "storage journal record is corrupt",
            Self::InvalidOutboxItemId => "storage outbox item id is invalid",
            Self::InvalidOutboxRevision => "storage outbox revision is invalid",
            Self::InvalidOutboxTimestamp => "storage outbox timestamp is invalid",
            Self::InvalidOutboxLease => "storage outbox lease is invalid",
            Self::InvalidOutboxLeaseOwner => "storage outbox lease owner is invalid",
            Self::InvalidOutboxClaimLimit => "storage outbox claim limit is invalid",
            Self::InvalidDeliveryAttempt => "storage delivery attempt is invalid",
            Self::InvalidDeliveryEvidence => "storage delivery evidence is invalid",
            Self::OutboxItemNotFound => "storage outbox item was not found",
            Self::OutboxItemNotReady => "storage outbox item is not ready",
            Self::OutboxItemTerminal => "storage outbox item is terminal",
            Self::OutboxPlanConflict => "storage outbox plan conflicts with durable state",
            Self::OutboxLeaseConflict => "storage outbox lease conflicts with durable state",
            Self::OutboxLeaseExpired => "storage outbox lease expired",
            Self::OutboxRevisionConflict => "storage outbox revision conflicts with durable state",
            Self::CorruptOutboxRecord => "storage outbox record is corrupt",
            Self::InvalidProjectionId => "storage projection id is invalid",
            Self::InvalidProjectionGeneration => "storage projection generation is invalid",
            Self::InvalidProjectionRevision => "storage projection revision is invalid",
            Self::InvalidProjectionTimestamp => "storage projection timestamp is invalid",
            Self::InvalidProjectionInvalidation => "storage projection invalidation is invalid",
            Self::ProjectionCheckpointMismatch => {
                "storage projection checkpoint identity does not match"
            }
            Self::ProjectionCheckpointRegression => "storage projection checkpoint regressed",
            Self::ProjectionRevisionConflict => {
                "storage projection revision conflicts with durable state"
            }
            Self::InvalidRebuildTicketId => "storage projection rebuild ticket id is invalid",
            Self::InvalidRebuildTransition => "storage projection rebuild transition is invalid",
            Self::RebuildTicketTerminal => "storage projection rebuild ticket is terminal",
            Self::InvalidEventIndexShardId => "storage event-index shard id is invalid",
            Self::InvalidEventIndexRange => "storage event-index id range is invalid",
            Self::InvalidEventIndexArtifactPath => "storage event-index artifact path is invalid",
            Self::InvalidEventIndexShardCount => "storage event-index shard count is invalid",
            Self::InvalidEventIndexTimestamp => "storage event-index timestamp is invalid",
            Self::InvalidEventIndexManifest => "storage event-index manifest is invalid",
            Self::InvalidEventIndexCursor => "storage event-index cursor is invalid",
            Self::InvalidEventIndexCheckpoint => "storage event-index checkpoint is invalid",
            Self::DuplicateEventIndexShard => "storage event-index shard is duplicated",
            Self::CorruptProjectionRecord => "storage projection record is corrupt",
            Self::InvalidProjectionDocument => "storage projection document is invalid",
            Self::InvalidProjectionSnapshot => "storage projection snapshot is invalid",
            Self::CorruptProjectionDocument => "storage projection document is corrupt",
            Self::InvalidPrivateArtifactId => "storage private-artifact id is invalid",
            Self::InvalidPrivateArtifactKind => "storage private-artifact kind is invalid",
            Self::InvalidPrivateArtifactSchema => "storage private-artifact schema is invalid",
            Self::InvalidPrivateArtifactSecretReference => {
                "storage private-artifact secret reference is invalid"
            }
            Self::InvalidPrivateArtifactRetention => {
                "storage private-artifact retention is invalid"
            }
            Self::InvalidPrivateArtifactRevision => "storage private-artifact revision is invalid",
            Self::InvalidPrivateArtifactResealId => "storage private-artifact reseal id is invalid",
            Self::InvalidPrivateArtifactResealRequest => {
                "storage private-artifact reseal request is invalid"
            }
            Self::InvalidPrivateArtifactTimestamp => {
                "storage private-artifact timestamp is invalid"
            }
            Self::InvalidPrivateArtifactMetadata => "storage private-artifact metadata is invalid",
            Self::PrivateArtifactNotFound => "storage private artifact was not found",
            Self::PrivateArtifactConflict => {
                "storage private-artifact metadata conflicts with durable state"
            }
            Self::PrivateArtifactRevisionConflict => {
                "storage private-artifact revision conflicts with durable state"
            }
            Self::PrivateArtifactResealConflict => {
                "storage private-artifact reseal conflicts with durable state"
            }
            Self::PrivateArtifactPersistenceIndeterminate => {
                "storage private-artifact persistence outcome is indeterminate"
            }
            Self::PrivateArtifactRetentionActive => "storage private-artifact retention is active",
            Self::PrivateArtifactNotExpired => "storage private artifact has not expired",
            Self::PrivateArtifactTombstoned => "storage private artifact is tombstoned",
            Self::InvalidExpiredArtifactQueryLimit => {
                "storage expired-artifact query limit is invalid"
            }
            Self::CorruptPrivateArtifactMetadata => "storage private-artifact metadata is corrupt",
            Self::InvalidBackupId => "storage backup id is invalid",
            Self::InvalidBackupVersion => "storage backup version is invalid",
            Self::InvalidBackupTimestamp => "storage backup timestamp is invalid",
            Self::InvalidBackupMemberPath => "storage backup member path is invalid",
            Self::InvalidBackupMemberLength => "storage backup member length is invalid",
            Self::InvalidBackupManifest => "storage backup manifest is invalid",
            Self::DuplicateBackupMember => "storage backup member is duplicated",
            Self::BackupSecretPolicyViolation => "storage backup secret policy was violated",
            Self::BackupManifestPlanMismatch => "storage backup manifest does not match its plan",
            Self::InvalidBackupTransition => "storage backup transition is invalid",
            Self::InvalidRestoreTimestamp => "storage restore timestamp is invalid",
            Self::InvalidRestoreTransition => "storage restore transition is invalid",
            Self::RestoreMemberVerificationFailed => "storage restore member verification failed",
            Self::InvalidReliabilityRevision => "storage reliability revision is invalid",
            Self::ReliabilityRevisionConflict => {
                "storage reliability revision conflicts with durable state"
            }
            Self::ReliabilityOperationTerminal => "storage reliability operation is terminal",
            Self::CorruptReliabilityOperation => "storage reliability operation is corrupt",
            Self::InvalidIntegrityStatus => "storage integrity status is invalid",
            Self::InvalidStorageStatus => "storage status is invalid",
            Self::InvalidAtomicCommitId => "storage atomic commit id is invalid",
            Self::InvalidAtomicCommitTimestamp => "storage atomic commit timestamp is invalid",
            Self::AtomicCommitConflict => "storage atomic commit conflicts with durable state",
            Self::AtomicWorkflowMismatch => "storage atomic workflow components do not match",
            Self::AtomicCommitFailed => "storage atomic workflow did not commit",
        })
    }
}

impl std::error::Error for Error {}

#[cfg(test)]
mod tests {
    use super::Error::*;

    #[test]
    fn every_storage_error_has_a_stable_nonempty_message() {
        let errors = [
            InvalidAuthoredOperation,
            InvalidAuthoredArtifact,
            InvalidAuthoredTransition,
            InvalidAuthoredDeliveryPlan,
            DeliveryPlanClaimConflict,
            DeliveryAttemptOverflow,
            InvalidWorkClaim,
            InvalidWorkFailure,
            InvalidRetrySchedule,
            InvalidSourceGeneration,
            InvalidEventSequence,
            InvalidEventQueryLimit,
            EmptyEventQueryIds,
            TooManyEventQueryIds,
            DuplicateEventQueryId,
            AdmissionEventMismatch,
            AdmissionRegression,
            EventConflict,
            EventPageLimitExceeded,
            CursorGenerationMismatch,
            SourceGenerationChanged,
            EventNotFound,
            CorruptStoredEvent,
            BackendUnavailable,
            InvalidOperationInstanceId,
            InvalidIdempotencyKey,
            InvalidOperationTimestamp,
            InvalidJournalRevision,
            InvalidRecoveryAttempt,
            InvalidRecoveryDeadline,
            InvalidJournalQueryLimit,
            IdempotencyConflict,
            OperationNotFound,
            OperationIdentityMismatch,
            JournalRevisionConflict,
            InvalidJournalTransition,
            JournalOperationCommitted,
            CorruptJournalRecord,
            InvalidOutboxItemId,
            InvalidOutboxRevision,
            InvalidOutboxTimestamp,
            InvalidOutboxLease,
            InvalidOutboxLeaseOwner,
            InvalidOutboxClaimLimit,
            InvalidDeliveryAttempt,
            InvalidDeliveryEvidence,
            OutboxItemNotFound,
            OutboxItemNotReady,
            OutboxItemTerminal,
            OutboxPlanConflict,
            OutboxLeaseConflict,
            OutboxLeaseExpired,
            OutboxRevisionConflict,
            CorruptOutboxRecord,
            InvalidProjectionId,
            InvalidProjectionGeneration,
            InvalidProjectionRevision,
            InvalidProjectionTimestamp,
            InvalidProjectionInvalidation,
            ProjectionCheckpointMismatch,
            ProjectionCheckpointRegression,
            ProjectionRevisionConflict,
            InvalidRebuildTicketId,
            InvalidRebuildTransition,
            RebuildTicketTerminal,
            InvalidEventIndexShardId,
            InvalidEventIndexRange,
            InvalidEventIndexArtifactPath,
            InvalidEventIndexShardCount,
            InvalidEventIndexTimestamp,
            InvalidEventIndexManifest,
            InvalidEventIndexCursor,
            InvalidEventIndexCheckpoint,
            DuplicateEventIndexShard,
            CorruptProjectionRecord,
            InvalidProjectionDocument,
            InvalidProjectionSnapshot,
            CorruptProjectionDocument,
            InvalidPrivateArtifactId,
            InvalidPrivateArtifactKind,
            InvalidPrivateArtifactSchema,
            InvalidPrivateArtifactSecretReference,
            InvalidPrivateArtifactRetention,
            InvalidPrivateArtifactRevision,
            InvalidPrivateArtifactResealId,
            InvalidPrivateArtifactResealRequest,
            InvalidPrivateArtifactTimestamp,
            InvalidPrivateArtifactMetadata,
            PrivateArtifactNotFound,
            PrivateArtifactConflict,
            PrivateArtifactRevisionConflict,
            PrivateArtifactResealConflict,
            PrivateArtifactPersistenceIndeterminate,
            PrivateArtifactRetentionActive,
            PrivateArtifactNotExpired,
            PrivateArtifactTombstoned,
            InvalidExpiredArtifactQueryLimit,
            CorruptPrivateArtifactMetadata,
            InvalidBackupId,
            InvalidBackupVersion,
            InvalidBackupTimestamp,
            InvalidBackupMemberPath,
            InvalidBackupMemberLength,
            InvalidBackupManifest,
            DuplicateBackupMember,
            BackupSecretPolicyViolation,
            BackupManifestPlanMismatch,
            InvalidBackupTransition,
            InvalidRestoreTimestamp,
            InvalidRestoreTransition,
            RestoreMemberVerificationFailed,
            InvalidReliabilityRevision,
            ReliabilityRevisionConflict,
            ReliabilityOperationTerminal,
            CorruptReliabilityOperation,
            InvalidIntegrityStatus,
            InvalidStorageStatus,
            InvalidAtomicCommitId,
            InvalidAtomicCommitTimestamp,
            AtomicCommitConflict,
            AtomicWorkflowMismatch,
            AtomicCommitFailed,
        ];
        for error in errors {
            assert!(!error.to_string().is_empty());
        }
    }
}
