[package]
name = "radroots_mesh_agent_proto"
publish = false
version = "0.1.0-alpha.2"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Mesh agent protocol schema for Radroots"
repository.workspace = true
homepage.workspace = true
readme = "README"

[features]
default = []

[dependencies]
sha2 = { workspace = true, default-features = false }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
