[package]
name = "radroots_replica_schema"
publish = false
version = "1.0.0-alpha.1"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Replica schema model for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_replica_schema"
readme = "README"

[lib]
crate-type = ["rlib"]

[features]
default = []
dto-bindgen = ["dep:dto_bindgen_core"]

[dependencies]
dto_bindgen_core = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
