[package]
name = "radroots_sql_core"
publish = false
version = "1.0.0-alpha.1"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "SQL support layer for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_sql_core"
readme = "README"

[lib]
crate-type = ["rlib"]

[features]
default = ["std"]
std = ["dep:chrono", "dep:uuid", "serde/std", "serde_json/std"]
web = ["std", "uuid/js"]
native = ["std", "dep:futures-executor", "dep:sqlx", "sqlx/sqlite-bundled"]
embedded = []

[dependencies]
serde_json = { workspace = true }
futures-executor = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true, features = ["derive"] }
chrono = { workspace = true, optional = true }
serde = { workspace = true }
uuid = { workspace = true, optional = true }
