import { RadrootsCoreDiscountValue, RadrootsCoreMoney, RadrootsCorePercent, RadrootsCoreQuantity, RadrootsCoreQuantityPrice } from "@radroots/core-bindings";

/*
 Generated by typeshare 1.13.3
*/

export type RadrootsListingPrice = RadrootsCoreQuantityPrice;

export interface JobPaymentRequest {
	amount_sat: number;
	bolt11?: string;
}

export interface RadrootsNostrEventRef {
	id: string;
	author: string;
	kind: number;
	d_tag?: string;
	relays?: string[];
}

export interface RadrootsComment {
	root: RadrootsNostrEventRef;
	parent: RadrootsNostrEventRef;
	content: string;
}

export interface RadrootsNostrEvent {
	id: string;
	author: string;
	created_at: number;
	kind: number;
	tags: string[][];
	content: string;
	sig: string;
}

export interface RadrootsCommentEventMetadata {
	id: string;
	author: string;
	published_at: number;
	comment: RadrootsComment;
}

export interface RadrootsCommentEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsCommentEventMetadata;
}

export interface RadrootsFollowProfile {
	published_at: number;
	public_key: string;
	relay_url?: string;
	contact_name?: string;
}

export interface RadrootsFollow {
	list: RadrootsFollowProfile[];
}

export interface RadrootsFollowEventMetadata {
	id: string;
	author: string;
	published_at: number;
	follow: RadrootsFollow;
}

export interface RadrootsFollowEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsFollowEventMetadata;
}

export enum JobFeedbackStatus {
	PaymentRequired = "payment_required",
	Processing = "processing",
	Error = "error",
	Success = "success",
	Partial = "partial",
}

export interface RadrootsNostrEventPtr {
	id: string;
	relays?: string;
}

export interface RadrootsJobFeedback {
	kind: number;
	status: JobFeedbackStatus;
	extra_info?: string;
	request_event: RadrootsNostrEventPtr;
	customer_pubkey?: string;
	payment?: JobPaymentRequest;
	content?: string;
	encrypted: boolean;
}

export interface RadrootsJobFeedbackEventMetadata {
	id: string;
	author: string;
	published_at: number;
	job_feedback: RadrootsJobFeedback;
}

export interface RadrootsJobFeedbackEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsJobFeedbackEventMetadata;
}

export enum JobInputType {
	Url = "url",
	Event = "event",
	Job = "job",
	Text = "text",
}

export interface RadrootsJobInput {
	data: string;
	input_type: JobInputType;
	relay?: string;
	marker?: string;
}

export interface RadrootsJobParam {
	key: string;
	value: string;
}

export interface RadrootsJobRequest {
	kind: number;
	inputs: RadrootsJobInput[];
	output?: string;
	params: RadrootsJobParam[];
	bid_sat?: number;
	relays: string[];
	providers: string[];
	topics: string[];
	encrypted: boolean;
}

export interface RadrootsJobRequestEventMetadata {
	id: string;
	author: string;
	published_at: number;
	job_request: RadrootsJobRequest;
}

export interface RadrootsJobRequestEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsJobRequestEventMetadata;
}

export interface RadrootsJobResult {
	kind: number;
	request_event: RadrootsNostrEventPtr;
	request_json?: string;
	inputs: RadrootsJobInput[];
	customer_pubkey?: string;
	payment?: JobPaymentRequest;
	content?: string;
	encrypted: boolean;
}

export interface RadrootsJobResultEventMetadata {
	id: string;
	author: string;
	published_at: number;
	job_result: RadrootsJobResult;
}

export interface RadrootsJobResultEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsJobResultEventMetadata;
}

export interface RadrootsListingProduct {
	key: string;
	title: string;
	category: string;
	summary?: string;
	process?: string;
	lot?: string;
	location?: string;
	profile?: string;
	year?: string;
}

export interface RadrootsListingQuantity {
	value: RadrootsCoreQuantity;
	label?: string;
	count?: number;
}

export type RadrootsListingDiscount = 
	| { kind: "quantity", amount: {
	ref_quantity: string;
	threshold: RadrootsCoreQuantity;
	value: RadrootsCoreMoney;
}}
	| { kind: "mass", amount: {
	threshold: RadrootsCoreQuantity;
	value: RadrootsCoreMoney;
}}
	| { kind: "subtotal", amount: {
	threshold: RadrootsCoreMoney;
	value: RadrootsCoreDiscountValue;
}}
	| { kind: "total", amount: {
	total_min: RadrootsCoreMoney;
	value: RadrootsCorePercent;
}};

export interface RadrootsListingLocation {
	primary: string;
	city?: string;
	region?: string;
	country?: string;
	lat?: number;
	lng?: number;
	geohash?: string;
}

export interface RadrootsListingImageSize {
	w: number;
	h: number;
}

export interface RadrootsListingImage {
	url: string;
	size?: RadrootsListingImageSize;
}

export interface RadrootsListing {
	d_tag: string;
	product: RadrootsListingProduct;
	quantities: RadrootsListingQuantity[];
	prices: RadrootsListingPrice[];
	discounts?: RadrootsListingDiscount[];
	location?: RadrootsListingLocation;
	images?: RadrootsListingImage[];
}

export interface RadrootsListingEventMetadata {
	id: string;
	author: string;
	published_at: number;
	listing: RadrootsListing;
}

export interface RadrootsListingEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsListingEventMetadata;
}

export interface RadrootsProfile {
	name: string;
	display_name?: string;
	nip05?: string;
	about?: string;
	website?: string;
	picture?: string;
	banner?: string;
	lud06?: string;
	lud16?: string;
	bot?: string;
}

export interface RadrootsProfileEventMetadata {
	id: string;
	author: string;
	published_at: number;
	profile: RadrootsProfile;
}

export interface RadrootsProfileEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsProfileEventMetadata;
}

export interface RadrootsReaction {
	root: RadrootsNostrEventRef;
	content: string;
}

export interface RadrootsReactionEventMetadata {
	id: string;
	author: string;
	published_at: number;
	reaction: RadrootsReaction;
}

export interface RadrootsReactionEventIndex {
	event: RadrootsNostrEvent;
	metadata: RadrootsReactionEventMetadata;
}

export const KIND_APPLICATION_HANDLER: number = 31990;
export const KIND_JOB_REQUEST_MIN: number = 5000;
export const KIND_JOB_REQUEST_MAX: number = 5999;
export const KIND_JOB_RESULT_MIN: number = 6000;
export const KIND_JOB_RESULT_MAX: number = 6999;
export const KIND_JOB_FEEDBACK: number = 7000;
