/*
 Generated by typeshare 1.13.3
*/

export const KIND_APPLICATION_HANDLER: number = 31990;
export const KIND_JOB_REQUEST_MIN: number = 5000;
export const KIND_JOB_REQUEST_MAX: number = 5999;
export const KIND_JOB_RESULT_MIN: number = 6000;
export const KIND_JOB_RESULT_MAX: number = 6999;
export const KIND_JOB_FEEDBACK: number = 7000;
