/*
 Generated by typeshare 1.13.3
*/

export const KIND_PROFILE: number = 0;
export const KIND_POST: number = 1;
export const KIND_FOLLOW: number = 3;
export const KIND_REACTION: number = 7;
export const KIND_MESSAGE: number = 14;
export const KIND_COMMENT: number = 1111;
export const KIND_APP_DATA: number = 30078;
export const KIND_LISTING: number = 30402;
export const KIND_APPLICATION_HANDLER: number = 31990;
export const KIND_JOB_REQUEST_MIN: number = 5000;
export const KIND_JOB_REQUEST_MAX: number = 5999;
export const KIND_JOB_RESULT_MIN: number = 6000;
export const KIND_JOB_RESULT_MAX: number = 6999;
export const KIND_JOB_FEEDBACK: number = 7000;
