import type { RadrootsCoreDecimal, RadrootsCoreDiscountValue, RadrootsCoreMoney, RadrootsCorePercent, RadrootsCoreQuantity, RadrootsCoreQuantityPrice } from "@radroots/core-bindings";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobFeedbackStatus = "payment_required" | "processing" | "error" | "success" | "partial";

export type JobInputType = "url" | "event" | "job" | "text";

export type JobPaymentRequest = { amount_sat: number, bolt11?: string | null, };

export type RadrootsActorType = "person" | "farm";

export type RadrootsAppData = { d_tag: string, content: string, };

export type RadrootsAppDataEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsAppDataEventMetadata, };

export type RadrootsAppDataEventMetadata = { id: string, author: string, published_at: number, kind: number, app_data: RadrootsAppData, };

export type RadrootsComment = { root: RadrootsNostrEventRef, parent: RadrootsNostrEventRef, content: string, };

export type RadrootsCommentEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsCommentEventMetadata, };

export type RadrootsCommentEventMetadata = { id: string, author: string, published_at: number, kind: number, comment: RadrootsComment, };

export type RadrootsFarm = { d_tag: string, name: string, about?: string | null, website?: string | null, picture?: string | null, banner?: string | null, location?: RadrootsFarmLocation | null, tags?: string[] | null, };

export type RadrootsFarmEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsFarmEventMetadata, };

export type RadrootsFarmEventMetadata = { id: string, author: string, published_at: number, kind: number, farm: RadrootsFarm, };

export type RadrootsFarmLocation = { primary: string, city?: string | null, region?: string | null, country?: string | null, lat?: number | null, lng?: number | null, geohash?: string | null, };

export type RadrootsFarmRef = { pubkey: string, d_tag: string, };

export type RadrootsFollow = { list: Array<RadrootsFollowProfile>, };

export type RadrootsFollowEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsFollowEventMetadata, };

export type RadrootsFollowEventMetadata = { id: string, author: string, published_at: number, kind: number, follow: RadrootsFollow, };

export type RadrootsFollowProfile = { published_at: number, public_key: string, relay_url?: string | null, contact_name?: string | null, };

export type RadrootsGiftWrap = { recipient: RadrootsGiftWrapRecipient, content: string, expiration?: number | null, };

export type RadrootsGiftWrapEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsGiftWrapEventMetadata, };

export type RadrootsGiftWrapEventMetadata = { id: string, author: string, published_at: number, kind: number, gift_wrap: RadrootsGiftWrap, };

export type RadrootsGiftWrapRecipient = { public_key: string, relay_url?: string | null, };

export type RadrootsJobFeedback = { kind: number, status: JobFeedbackStatus, extra_info?: string | null, request_event: RadrootsNostrEventPtr, customer_pubkey?: string | null, payment?: JobPaymentRequest | null, content?: string | null, encrypted: boolean, };

export type RadrootsJobFeedbackEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsJobFeedbackEventMetadata, };

export type RadrootsJobFeedbackEventMetadata = { id: string, author: string, published_at: number, kind: number, job_feedback: RadrootsJobFeedback, };

export type RadrootsJobInput = { data: string, input_type: JobInputType, relay?: string | null, marker?: string | null, };

export type RadrootsJobParam = { key: string, value: string, };

export type RadrootsJobRequest = { kind: number, inputs: Array<RadrootsJobInput>, output?: string | null, params: Array<RadrootsJobParam>, bid_sat?: number | null, relays: Array<string>, providers: Array<string>, topics: Array<string>, encrypted: boolean, };

export type RadrootsJobRequestEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsJobRequestEventMetadata, };

export type RadrootsJobRequestEventMetadata = { id: string, author: string, published_at: number, kind: number, job_request: RadrootsJobRequest, };

export type RadrootsJobResult = { kind: number, request_event: RadrootsNostrEventPtr, request_json?: string | null, inputs: Array<RadrootsJobInput>, customer_pubkey?: string | null, payment?: JobPaymentRequest | null, content?: string | null, encrypted: boolean, };

export type RadrootsJobResultEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsJobResultEventMetadata, };

export type RadrootsJobResultEventMetadata = { id: string, author: string, published_at: number, kind: number, job_result: RadrootsJobResult, };

export type RadrootsList = { content: string, entries: Array<RadrootsListEntry>, };

export type RadrootsListEntry = { tag: string, values: Array<string>, };

export type RadrootsListEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsListEventMetadata, };

export type RadrootsListEventMetadata = { id: string, author: string, published_at: number, kind: number, list: RadrootsList, };

export type RadrootsListSet = { d_tag: string, content: string, entries: Array<RadrootsListEntry>, title?: string | null, description?: string | null, image?: string | null, };

export type RadrootsListSetEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsListSetEventMetadata, };

export type RadrootsListSetEventMetadata = { id: string, author: string, published_at: number, kind: number, list_set: RadrootsListSet, };

export type RadrootsListing = { d_tag: string, product: RadrootsListingProduct, quantities: Array<RadrootsListingQuantity>, prices: RadrootsCoreQuantityPrice[], discounts?: RadrootsListingDiscount[] | null, inventory_available?: RadrootsCoreDecimal | null, availability?: RadrootsListingAvailability | null, delivery_method?: RadrootsListingDeliveryMethod | null, location?: RadrootsListingLocation | null, images?: RadrootsListingImage[] | null, };

export type RadrootsListingAvailability = { "kind": "window", "amount": { start?: number | null, end?: number | null, } } | { "kind": "status", "amount": { status: RadrootsListingStatus, } };

export type RadrootsListingDeliveryMethod = { "kind": "pickup" } | { "kind": "local_delivery" } | { "kind": "shipping" } | { "kind": "other", "amount": { method: string, } };

export type RadrootsListingDiscount = { "kind": "quantity", "amount": { ref_quantity: string, threshold: RadrootsCoreQuantity, value: RadrootsCoreMoney, } } | { "kind": "mass", "amount": { threshold: RadrootsCoreQuantity, value: RadrootsCoreMoney, } } | { "kind": "subtotal", "amount": { threshold: RadrootsCoreMoney, value: RadrootsCoreDiscountValue, } } | { "kind": "total", "amount": { total_min: RadrootsCoreMoney, value: RadrootsCorePercent, } };

export type RadrootsListingEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsListingEventMetadata, };

export type RadrootsListingEventMetadata = { id: string, author: string, published_at: number, kind: number, listing: RadrootsListing, };

export type RadrootsListingImage = { url: string, size?: RadrootsListingImageSize | null, };

export type RadrootsListingImageSize = { w: number, h: number, };

export type RadrootsListingLocation = { primary: string, city?: string | null, region?: string | null, country?: string | null, lat?: number | null, lng?: number | null, geohash?: string | null, };

export type RadrootsListingProduct = { key: string, title: string, category: string, summary?: string | null, process?: string | null, lot?: string | null, location?: string | null, profile?: string | null, year?: string | null, };

export type RadrootsListingProductTagKeys = readonly ["key", "title", "category", "summary", "process", "lot", "location", "profile", "year"];

export type RadrootsListingQuantity = { value: RadrootsCoreQuantity, label?: string | null, count?: number | null, };

export type RadrootsListingStatus = { "kind": "active" } | { "kind": "sold" } | { "kind": "other", "amount": { value: string, } };

export type RadrootsMessage = { recipients: Array<RadrootsMessageRecipient>, content: string, reply_to?: RadrootsNostrEventPtr | null, subject?: string | null, };

export type RadrootsMessageEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsMessageEventMetadata, };

export type RadrootsMessageEventMetadata = { id: string, author: string, published_at: number, kind: number, message: RadrootsMessage, };

export type RadrootsMessageFile = { recipients: Array<RadrootsMessageRecipient>, file_url: string, reply_to?: RadrootsNostrEventPtr | null, subject?: string | null, file_type: string, encryption_algorithm: string, decryption_key: string, decryption_nonce: string, encrypted_hash: string, original_hash?: string | null, size?: number | null, dimensions?: RadrootsMessageFileDimensions | null, blurhash?: string | null, thumb?: string | null, fallbacks: Array<string>, };

export type RadrootsMessageFileDimensions = { w: number, h: number, };

export type RadrootsMessageFileEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsMessageFileEventMetadata, };

export type RadrootsMessageFileEventMetadata = { id: string, author: string, published_at: number, kind: number, message_file: RadrootsMessageFile, };

export type RadrootsMessageRecipient = { public_key: string, relay_url?: string | null, };

export type RadrootsNostrEvent = { id: string, author: string, created_at: number, kind: number, tags: Array<Array<string>>, content: string, sig: string, };

export type RadrootsNostrEventPtr = { id: string, relays?: string | null, };

export type RadrootsNostrEventRef = { id: string, author: string, kind: number, d_tag?: string | null, relays?: string[] | null, };

export type RadrootsPlot = { d_tag: string, farm: RadrootsFarmRef, name: string, about?: string | null, location?: RadrootsPlotLocation | null, geometry?: string | null, tags?: string[] | null, };

export type RadrootsPlotEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsPlotEventMetadata, };

export type RadrootsPlotEventMetadata = { id: string, author: string, published_at: number, kind: number, plot: RadrootsPlot, };

export type RadrootsPlotLocation = { primary: string, city?: string | null, region?: string | null, country?: string | null, lat?: number | null, lng?: number | null, geohash?: string | null, };

export type RadrootsPost = { content: string, };

export type RadrootsPostEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsPostEventMetadata, };

export type RadrootsPostEventMetadata = { id: string, author: string, published_at: number, kind: number, post: RadrootsPost, };

export type RadrootsProfile = { name: string, display_name?: string | null, nip05?: string | null, about?: string | null, website?: string | null, picture?: string | null, banner?: string | null, lud06?: string | null, lud16?: string | null, bot?: string | null, };

export type RadrootsProfileEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsProfileEventMetadata, };

export type RadrootsProfileEventMetadata = { id: string, author: string, published_at: number, kind: number, actor?: RadrootsActorType | null, profile: RadrootsProfile, };

export type RadrootsReaction = { root: RadrootsNostrEventRef, content: string, };

export type RadrootsReactionEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsReactionEventMetadata, };

export type RadrootsReactionEventMetadata = { id: string, author: string, published_at: number, kind: number, reaction: RadrootsReaction, };

export type RadrootsRelayDocument = { name?: string | null, description?: string | null, pubkey?: string | null, contact?: string | null, supported_nips?: number[] | null, software?: string | null, version?: string | null, };

export type RadrootsSeal = { content: string, };

export type RadrootsSealEventIndex = { event: RadrootsNostrEvent, metadata: RadrootsSealEventMetadata, };

export type RadrootsSealEventMetadata = { id: string, author: string, published_at: number, kind: number, seal: RadrootsSeal, };
