[package]
name = "radroots_runtime_store"
publish = false
version = "0.1.0-alpha"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Runtime store workspace for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_runtime_store"
readme = "README"

[lib]
crate-type = ["rlib"]

[features]
default = []
native = ["radroots_sql_core/native"]

[dependencies]
radroots_sql_core = { workspace = true, features = ["std"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
radroots_sql_core = { workspace = true, features = ["native"] }
