[profiles.default]
no_default_features = false
features = []
test_threads = 1

[profiles.crates."radroots_log"]
no_default_features = true
features = []
test_threads = 1

[profiles.crates."radroots_event_codec"]
no_default_features = false
features = ["json"]
test_threads = 1

[profiles.crates."radroots_nostr"]
no_default_features = false
features = ["blossom"]
test_threads = 1

[profiles.crates."radroots_replica_sync"]
no_default_features = false
features = ["legacy-ingest"]
test_threads = 1

[profiles.crates."radroots_sdk"]
no_default_features = false
features = ["full"]
test_threads = 1
