[package]
name = "xtask"
version = "0.1.0-alpha"
edition.workspace = true
rust-version.workspace = true
description = "Workspace task runner for Radroots Rust crates"
readme = "README"
license.workspace = true
publish = false
authors = ["Tyson Lupul <tyson@radroots.org>"]

[dependencies]
clap = { workspace = true, features = ["derive"] }
dto_bindgen_core = { workspace = true }
dto_bindgen_backend_ts = { workspace = true }
fs2 = { workspace = true }
flate2 = { workspace = true }
hex = { workspace = true }
jsonschema = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
radroots_event_codec = { workspace = true, features = [
  "manifests",
], default-features = false }
radroots_core_bindings = { workspace = true }
radroots_event_bindings = { workspace = true }
radroots_identity = { workspace = true }
radroots_identity_bindings = { workspace = true }
radroots_protocol = { workspace = true, features = ["std"] }
radroots_replica_schema_bindings = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
syn = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
