[package]
name = "radroots_nostr_connect"
publish = false
version = "0.1.0-alpha"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
description = "NIP-46 protocol model for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_nostr_connect"
readme = "README.md"

[lib]
name = "radroots_nostr_connect"

[dependencies]
nostr = { workspace = true, features = ["std", "nip44"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
