[release]
version = "0.1.0-alpha.1"

[publish]
crates = [
  "radroots-core",
  "radroots-types",
  "radroots-events",
  "radroots-log",
  "radroots-runtime",
  "radroots-identity",
  "radroots-trade",
  "radroots-events-codec",
  "radroots-events-codec-wasm",
  "radroots-events-indexed",
  "radroots-nostr",
  "radroots-replica-db-schema",
  "radroots-sql-wasm-bridge",
  "radroots-nostr-runtime",
  "radroots-sql-core",
  "radroots-nostr-ndb",
  "radroots-replica-db",
  "radroots-sql-wasm-core",
  "radroots-nostr-accounts",
  "radroots-replica-sync",
  "radroots-net-core",
  "radroots-replica-db-wasm",
  "radroots-replica-sync-wasm",
  "radroots-app-core",
  "radroots-net",
  "radroots-app-wasm",
]

[internal]
crates = [
  "xtask",
]

[publish_order]
crates = [
  "radroots-core",
  "radroots-types",
  "radroots-log",
  "radroots-events",
  "radroots-runtime",
  "radroots-events-codec",
  "radroots-identity",
  "radroots-trade",
  "radroots-events-codec-wasm",
  "radroots-events-indexed",
  "radroots-nostr",
  "radroots-replica-db-schema",
  "radroots-sql-wasm-bridge",
  "radroots-nostr-runtime",
  "radroots-sql-core",
  "radroots-nostr-ndb",
  "radroots-replica-db",
  "radroots-sql-wasm-core",
  "radroots-nostr-accounts",
  "radroots-replica-sync",
  "radroots-net-core",
  "radroots-replica-db-wasm",
  "radroots-replica-sync-wasm",
  "radroots-app-core",
  "radroots-net",
  "radroots-app-wasm",
]
