[package]
name = "radroots_test_fixtures"
version = "0.1.0-alpha"
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/radrootslabs/lib"
homepage = "https://radroots.org"
readme = "README"
publish = false
description = "Shared fixture library for Radroots"
authors = ["Tyson Lupul <tyson@radroots.org>"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
radroots_event = { workspace = true, features = [
  "std",
  "serde",
  "knowledge",
] }
radroots_identity = { workspace = true }
