[package]
name = "radroots-identity"
publish = false
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Identity model for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots-identity"
readme = "README.md"

[lib]
name = "radroots_identity"

[features]
default = ["std", "json-file", "nip49"]
std = [
  "dep:radroots_protected_store",
  "dep:radroots_runtime_paths",
  "dep:radroots_secret_vault",
]
json-file = ["std", "dep:radroots_runtime"]
nip49 = ["std", "nostr/nip49"]
secrecy = ["dep:secrecy"]
zeroize = ["dep:zeroize"]

[dependencies]
radroots_runtime = { workspace = true, optional = true }
radroots_protected_store = { workspace = true, optional = true, features = [
  "std",
] }
radroots_runtime_paths = { workspace = true, optional = true }
radroots_secret_vault = { workspace = true, optional = true, features = [
  "std",
] }
nostr = { workspace = true }
secrecy = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
