[package]
name = "radroots_storage_sqlite"
description = "SQLite storage backend for Radroots"
version = "0.1.0-alpha"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme = "README.md"
publish = false

[lib]
name = "radroots_storage_sqlite"

[dependencies]
radroots_event_codec = { workspace = true, default-features = false }
radroots_secrets = { workspace = true, default-features = false }
radroots_storage = { workspace = true, default-features = false }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
