/*
 Generated by typeshare 1.13.3
*/

export type RadrootsEventsIndexedShardId = string;

export interface RadrootsEventsIndexedIdRange {
	start: string;
	end: string;
}

export interface RadrootsEventsIndexedShardCheckpoint {
	shard_id: RadrootsEventsIndexedShardId;
	last_created_at: number;
	last_event_id?: string;
	cursor?: string;
}

export interface RadrootsEventsIndexedIndexCheckpoint {
	generated_at: number;
	shards: RadrootsEventsIndexedShardCheckpoint[];
}

export interface RadrootsEventsIndexedShardMetadata {
	file: string;
	count: number;
	first_id: string;
	last_id: string;
	first_published_at: number;
	last_published_at: number;
	sha256: string;
}

export interface RadrootsEventsIndexedManifest {
	country: string;
	total: number;
	shard_size: number;
	first_published_at: number;
	last_published_at: number;
	shards: RadrootsEventsIndexedShardMetadata[];
}

