[package]
name = "radroots_protocol_contract_v1"
publish = false
version = "0.1.0-alpha"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Protocol Contract V1 descriptors for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_protocol_contract_v1"
readme = "README"

[features]
default = ["std", "serde"]
serde = ["dep:serde"]
std = []

[dependencies]
serde = { workspace = true, default-features = false, features = [
  "alloc",
  "derive",
], optional = true }

[dev-dependencies]
radroots_protocol = { workspace = true, default-features = false, features = [
  "serde",
  "std",
] }
serde_json = { workspace = true, features = ["std"] }
