[package]
name = "studio_app_core_uniffi_bindgen"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "studio-app-core-uniffi-bindgen"
path = "src/main.rs"

[dependencies]
uniffi = { version = "=0.32.0", features = ["cli"] }
