[package]
name = "radroots-studio-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
radroots-studio-application = { path = "../application" }
radroots-studio-domain = { path = "../domain" }
keyring.workspace = true
refinery.workspace = true
rusqlite.workspace = true

[dev-dependencies]
tempfile = "=3.23.0"

[lints]
workspace = true
