[package]
name = "radroots_geocoder"
publish = false
version = "1.0.0-alpha.1"
edition.workspace = true
authors = ["Tyson Lupul <tyson@radroots.org>"]
rust-version.workspace = true
license.workspace = true
description = "Location model for Radroots"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/radroots_geocoder"
readme = "README"

[features]
test-fixture-geonames-asset = []

[dependencies]
hex = { workspace = true }
futures-executor = { workspace = true }
radroots_runtime_paths = { workspace = true }
reqwest = { workspace = true, features = ["hickory-dns", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
sqlx = { workspace = true, features = ["derive", "sqlite-bundled"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }
url = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
