schema_version = 1

[package]
name = "libsqlite3-sys"
version = "0.37.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b1f111c8c41e7c61a49cd34e44c7619462967221a6443b0ec299e0ac30cfb9b1"

[activation]
route = [
  "radroots_event_store/sqlite",
  "sqlx/sqlite-bundled",
  "libsqlite3-sys/bundled",
]
