name: nix-flake-ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  flake-check:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: install nix
        uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: run flake check
        run: nix flake check
